    .section .content_data.banim_data

    .global BANIM_IMG_armm_sp1_0
.align 2, 0
BANIM_IMG_armm_sp1_0: @ 0x086A1000
    .incbin "banims/armm_sp1/armm_sp1_0.4bpp.lz"

    .global BANIM_IMG_armm_sp1_1
.align 2, 0
BANIM_IMG_armm_sp1_1: @ 0x086A2488
    .incbin "banims/armm_sp1/armm_sp1_1.4bpp.lz"

    .global BANIM_IMG_armm_sp1_2
.align 2, 0
BANIM_IMG_armm_sp1_2: @ 0x086A3554
    .incbin "banims/armm_sp1/armm_sp1_2.4bpp.lz"

    .global BANIM_PAL_armm_sp1
.align 2, 0
BANIM_PAL_armm_sp1: @ 0x086A41E8
    .incbin "banims/armm_sp1/armm_sp1.agbpal.lz"

    .global BANIM_OAMR_armm_sp1
.align 2, 0
BANIM_OAMR_armm_sp1: @ 0x086A47F4
    .incbin "banims/armm_sp1/armm_sp1.oam.oamr.bin.lz"

    .global BANIM_IMG_pirm_ax1_0
.align 2, 0
BANIM_IMG_pirm_ax1_0: @ 0x086A50D4
    .incbin "banims/pirm_ax1/pirm_ax1_0.4bpp.lz"

    .global BANIM_IMG_pirm_ax1_1
.align 2, 0
BANIM_IMG_pirm_ax1_1: @ 0x086A63BC
    .incbin "banims/pirm_ax1/pirm_ax1_1.4bpp.lz"

    .global BANIM_PAL_pirm_ax1
.align 2, 0
BANIM_PAL_pirm_ax1: @ 0x086A7330
    .incbin "banims/pirm_ax1/pirm_ax1.agbpal.lz"

    .global BANIM_OAMR_pirm_ax1
.align 2, 0
BANIM_OAMR_pirm_ax1: @ 0x086A76BC
    .incbin "banims/pirm_ax1/pirm_ax1.oam.oamr.bin.lz"

    .global BANIM_IMG_berm_ax1_0
.align 2, 0
BANIM_IMG_berm_ax1_0: @ 0x086A7B98
    .incbin "banims/berm_ax1/berm_ax1_0.4bpp.lz"

    .global BANIM_IMG_berm_ax1_1
.align 2, 0
BANIM_IMG_berm_ax1_1: @ 0x086A8D8C
    .incbin "banims/berm_ax1/berm_ax1_1.4bpp.lz"

    .global BANIM_PAL_berm_ax1
.align 2, 0
BANIM_PAL_berm_ax1: @ 0x086A9EFC
    .incbin "banims/berm_ax1/berm_ax1.agbpal.lz"

    .global BANIM_OAMR_berm_ax1
.align 2, 0
BANIM_OAMR_berm_ax1: @ 0x086AA808
    .incbin "banims/berm_ax1/berm_ax1.oam.oamr.bin.lz"

    .global BANIM_IMG_banm_ax1_0
.align 2, 0
BANIM_IMG_banm_ax1_0: @ 0x086AB360
    .incbin "banims/banm_ax1/banm_ax1_0.4bpp.lz"

    .global BANIM_IMG_banm_ax1_1
.align 2, 0
BANIM_IMG_banm_ax1_1: @ 0x086AC5B8
    .incbin "banims/banm_ax1/banm_ax1_1.4bpp.lz"

    .global BANIM_IMG_banm_ax1_3_1
.align 2, 0
BANIM_IMG_banm_ax1_3_1: @ 0x086AD808
    .incbin "banims/banm_ax1/banm_ax1_3_1.4bpp.lz"

    .global BANIM_PAL_banm_ax1
.align 2, 0
BANIM_PAL_banm_ax1: @ 0x086AE14C
    .incbin "banims/banm_ax1/banm_ax1.agbpal.lz"

    .global BANIM_OAMR_banm_ax1
.align 2, 0
BANIM_OAMR_banm_ax1: @ 0x086AE824
    .incbin "banims/banm_ax1/banm_ax1.oam.oamr.bin.lz"

    .global BANIM_IMG_snim_ar1_0
.align 2, 0
BANIM_IMG_snim_ar1_0: @ 0x086AF174
    .incbin "banims/snim_ar1/snim_ar1_0.4bpp.lz"

    .global BANIM_IMG_snim_ar1_1
.align 2, 0
BANIM_IMG_snim_ar1_1: @ 0x086AFCB8
    .incbin "banims/snim_ar1/snim_ar1_1.4bpp.lz"

    .global BANIM_IMG_snim_ar1_2
.align 2, 0
BANIM_IMG_snim_ar1_2: @ 0x086B06F0
    .incbin "banims/snim_ar1/snim_ar1_2.4bpp.lz"

    .global BANIM_PAL_snim_ar1
.align 2, 0
BANIM_PAL_snim_ar1: @ 0x086B0E9C
    .incbin "banims/snim_ar1/snim_ar1.agbpal.lz"

    .global BANIM_OAMR_snim_ar1
.align 2, 0
BANIM_OAMR_snim_ar1: @ 0x086B13A4
    .incbin "banims/snim_ar1/snim_ar1.oam.oamr.bin.lz"

    .global BANIM_IMG_snif_ar1_0
.align 2, 0
BANIM_IMG_snif_ar1_0: @ 0x086B1A90
    .incbin "banims/snif_ar1/snif_ar1_0.4bpp.lz"

    .global BANIM_IMG_snif_ar1_1
.align 2, 0
BANIM_IMG_snif_ar1_1: @ 0x086B259C
    .incbin "banims/snif_ar1/snif_ar1_1.4bpp.lz"

    .global BANIM_IMG_snif_ar1_2
.align 2, 0
BANIM_IMG_snif_ar1_2: @ 0x086B300C
    .incbin "banims/snif_ar1/snif_ar1_2.4bpp.lz"

    .global BANIM_PAL_snif_ar1
.align 2, 0
BANIM_PAL_snif_ar1: @ 0x086B376C
    .incbin "banims/snif_ar1/snif_ar1.agbpal.lz"

    .global BANIM_OAMR_snif_ar1
.align 2, 0
BANIM_OAMR_snif_ar1: @ 0x086B3C74
    .incbin "banims/snif_ar1/snif_ar1.oam.oamr.bin.lz"

    .global BANIM_IMG_merm_sw1_0
.align 2, 0
BANIM_IMG_merm_sw1_0: @ 0x086B4360
    .incbin "banims/merm_sw1/merm_sw1_0.4bpp.lz"

    .global BANIM_IMG_merm_sw1_1
.align 2, 0
BANIM_IMG_merm_sw1_1: @ 0x086B5608
    .incbin "banims/merm_sw1/merm_sw1_1.4bpp.lz"

    .global BANIM_IMG_merm_sw1_2
.align 2, 0
BANIM_IMG_merm_sw1_2: @ 0x086B67FC
    .incbin "banims/merm_sw1/merm_sw1_2.4bpp.lz"

    .global BANIM_IMG_merm_sw1_3
.align 2, 0
BANIM_IMG_merm_sw1_3: @ 0x086B7498
    .incbin "banims/merm_sw1/merm_sw1_3.4bpp.lz"

    .global BANIM_PAL_merm_sw1
.align 2, 0
BANIM_PAL_merm_sw1: @ 0x086B8284
    .incbin "banims/merm_sw1/merm_sw1.agbpal.lz"

    .global BANIM_OAMR_merm_sw1
.align 2, 0
BANIM_OAMR_merm_sw1: @ 0x086B8F68
    .incbin "banims/merm_sw1/merm_sw1.oam.oamr.bin.lz"

    .global BANIM_PAL_merm_sw1_2
.align 2, 0
BANIM_PAL_merm_sw1_2: @ 0x086BA114
    .incbin "banims/merm_sw1/merm_sw1.agbpal.lz"

    .global BANIM_OAMR_merm_sw1_2
.align 2, 0
BANIM_OAMR_merm_sw1_2: @ 0x086BA208
    .incbin "banims/merm_sw1/merm_sw1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_sokm_sp1_0
.align 2, 0
BANIM_IMG_sokm_sp1_0: @ 0x086BA344
    .incbin "banims/sokm_sp1/sokm_sp1_0.4bpp.lz"

    .global BANIM_IMG_sokm_sp1_1
.align 2, 0
BANIM_IMG_sokm_sp1_1: @ 0x086BB170
    .incbin "banims/sokm_sp1/sokm_sp1_1.4bpp.lz"

    .global BANIM_IMG_sokm_sp1_2
.align 2, 0
BANIM_IMG_sokm_sp1_2: @ 0x086BC240
    .incbin "banims/sokm_sp1/sokm_sp1_2.4bpp.lz"

    .global BANIM_IMG_sokm_sp1_3
.align 2, 0
BANIM_IMG_sokm_sp1_3: @ 0x086BD18C
    .incbin "banims/sokm_sp1/sokm_sp1_3.4bpp.lz"

    .global BANIM_PAL_sokm_sp1
.align 2, 0
BANIM_PAL_sokm_sp1: @ 0x086BE3E0
    .incbin "banims/sokm_sp1/sokm_sp1.agbpal.lz"

    .global BANIM_OAMR_sokm_sp1
.align 2, 0
BANIM_OAMR_sokm_sp1: @ 0x086BF078
    .incbin "banims/sokm_sp1/sokm_sp1.oam.oamr.bin.lz"

    .global BANIM_PAL_sokm_sp1_2
.align 2, 0
BANIM_PAL_sokm_sp1_2: @ 0x086C0004
    .incbin "banims/sokm_sp1/sokm_sp1.agbpal.lz"

    .global BANIM_OAMR_sokm_sp1_2
.align 2, 0
BANIM_OAMR_sokm_sp1_2: @ 0x086C0900
    .incbin "banims/sokm_sp1/sokm_sp1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_sokm_sp1_3
.align 2, 0
BANIM_PAL_sokm_sp1_3: @ 0x086C14B0
    .incbin "banims/sokm_sp1/sokm_sp1.agbpal.lz"

    .global BANIM_OAMR_sokm_sp1_3
.align 2, 0
BANIM_OAMR_sokm_sp1_3: @ 0x086C1600
    .incbin "banims/sokm_sp1/sokm_sp1_3.oam.oamr.bin.lz"

    .global BANIM_IMG_fakf_sp1_0
.align 2, 0
BANIM_IMG_fakf_sp1_0: @ 0x086C17C8
    .incbin "banims/fakf_sp1/fakf_sp1_0.4bpp.lz"

    .global BANIM_IMG_fakf_sp1_1
.align 2, 0
BANIM_IMG_fakf_sp1_1: @ 0x086C2870
    .incbin "banims/fakf_sp1/fakf_sp1_1.4bpp.lz"

    .global BANIM_IMG_fakf_sp1_2
.align 2, 0
BANIM_IMG_fakf_sp1_2: @ 0x086C3B4C
    .incbin "banims/fakf_sp1/fakf_sp1_2.4bpp.lz"

    .global BANIM_IMG_fakf_sp1_3
.align 2, 0
BANIM_IMG_fakf_sp1_3: @ 0x086C49E8
    .incbin "banims/fakf_sp1/fakf_sp1_3.4bpp.lz"

    .global BANIM_IMG_fakf_sp1_4
.align 2, 0
BANIM_IMG_fakf_sp1_4: @ 0x086C5D54
    .incbin "banims/fakf_sp1/fakf_sp1_4.4bpp.lz"

    .global BANIM_IMG_fakf_sp1_5
.align 2, 0
BANIM_IMG_fakf_sp1_5: @ 0x086C6D00
    .incbin "banims/fakf_sp1/fakf_sp1_5.4bpp.lz"

    .global BANIM_IMG_fakf_sp1_6
.align 2, 0
BANIM_IMG_fakf_sp1_6: @ 0x086C7CE8
    .incbin "banims/fakf_sp1/fakf_sp1_6.4bpp.lz"

    .global BANIM_IMG_fakf_sp1_7
.align 2, 0
BANIM_IMG_fakf_sp1_7: @ 0x086C8FC4
    .incbin "banims/fakf_sp1/fakf_sp1_7.4bpp.lz"

    .global BANIM_PAL_fakf_sp1
.align 2, 0
BANIM_PAL_fakf_sp1: @ 0x086CA180
    .incbin "banims/fakf_sp1/fakf_sp1.agbpal.lz"

    .global BANIM_OAMR_fakf_sp1
.align 2, 0
BANIM_OAMR_fakf_sp1: @ 0x086CB98C
    .incbin "banims/fakf_sp1/fakf_sp1.oam.oamr.bin.lz"

    .global BANIM_IMG_magm_mg1_0
.align 2, 0
BANIM_IMG_magm_mg1_0: @ 0x086CD5E4
    .incbin "banims/magm_mg1/magm_mg1_0.4bpp.lz"

    .global BANIM_IMG_magm_mg1_1
.align 2, 0
BANIM_IMG_magm_mg1_1: @ 0x086CE328
    .incbin "banims/magm_mg1/magm_mg1_1.4bpp.lz"

    .global BANIM_IMG_magm_mg1_2
.align 2, 0
BANIM_IMG_magm_mg1_2: @ 0x086CEF68
    .incbin "banims/magm_mg1/magm_mg1_2.4bpp.lz"

    .global BANIM_PAL_magm_mg1
.align 2, 0
BANIM_PAL_magm_mg1: @ 0x086CFACC
    .incbin "banims/magm_mg1/magm_mg1.agbpal.lz"

    .global BANIM_OAMR_magm_mg1
.align 2, 0
BANIM_OAMR_magm_mg1: @ 0x086CFDD8
    .incbin "banims/magm_mg1/magm_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_magf_mg1_0
.align 2, 0
BANIM_IMG_magf_mg1_0: @ 0x086D037C
    .incbin "banims/magf_mg1/magf_mg1_0.4bpp.lz"

    .global BANIM_IMG_magf_mg1_1
.align 2, 0
BANIM_IMG_magf_mg1_1: @ 0x086D1100
    .incbin "banims/magf_mg1/magf_mg1_1.4bpp.lz"

    .global BANIM_IMG_magf_mg1_2
.align 2, 0
BANIM_IMG_magf_mg1_2: @ 0x086D1DB8
    .incbin "banims/magf_mg1/magf_mg1_2.4bpp.lz"

    .global BANIM_PAL_magf_mg1
.align 2, 0
BANIM_PAL_magf_mg1: @ 0x086D29C0
    .incbin "banims/magf_mg1/magf_mg1.agbpal.lz"

    .global BANIM_OAMR_magf_mg1
.align 2, 0
BANIM_OAMR_magf_mg1: @ 0x086D2CCC
    .incbin "banims/magf_mg1/magf_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_arcm_ar1_0
.align 2, 0
BANIM_IMG_arcm_ar1_0: @ 0x086D3270
    .incbin "banims/arcm_ar1/arcm_ar1_0.4bpp.lz"

    .global BANIM_IMG_arcm_ar1_1
.align 2, 0
BANIM_IMG_arcm_ar1_1: @ 0x086D3F00
    .incbin "banims/arcm_ar1/arcm_ar1_1.4bpp.lz"

    .global BANIM_IMG_arcm_ar1_2
.align 2, 0
BANIM_IMG_arcm_ar1_2: @ 0x086D4A8C
    .incbin "banims/arcm_ar1/arcm_ar1_2.4bpp.lz"

    .global BANIM_PAL_arcm_ar1
.align 2, 0
BANIM_PAL_arcm_ar1: @ 0x086D5064
    .incbin "banims/arcm_ar1/arcm_ar1.agbpal.lz"

    .global BANIM_OAMR_arcm_ar1
.align 2, 0
BANIM_OAMR_arcm_ar1: @ 0x086D5540
    .incbin "banims/arcm_ar1/arcm_ar1.oam.oamr.bin.lz"

    .global BANIM_IMG_arcf_ar1_0
.align 2, 0
BANIM_IMG_arcf_ar1_0: @ 0x086D5BFC
    .incbin "banims/arcf_ar1/arcf_ar1_0.4bpp.lz"

    .global BANIM_IMG_arcf_ar1_1
.align 2, 0
BANIM_IMG_arcf_ar1_1: @ 0x086D6890
    .incbin "banims/arcf_ar1/arcf_ar1_1.4bpp.lz"

    .global BANIM_IMG_arcf_ar1_2
.align 2, 0
BANIM_IMG_arcf_ar1_2: @ 0x086D7400
    .incbin "banims/arcf_ar1/arcf_ar1_2.4bpp.lz"

    .global BANIM_PAL_arcf_ar1
.align 2, 0
BANIM_PAL_arcf_ar1: @ 0x086D79C8
    .incbin "banims/arcf_ar1/arcf_ar1.agbpal.lz"

    .global BANIM_OAMR_arcf_ar1
.align 2, 0
BANIM_OAMR_arcf_ar1: @ 0x086D7EA4
    .incbin "banims/arcf_ar1/arcf_ar1.oam.oamr.bin.lz"

    .global BANIM_IMG_lorm_sw1_0
.align 2, 0
BANIM_IMG_lorm_sw1_0: @ 0x086D8560
    .incbin "banims/lorm_sw1/lorm_sw1_0.4bpp.lz"

    .global BANIM_IMG_lorm_sw1_1
.align 2, 0
BANIM_IMG_lorm_sw1_1: @ 0x086D92FC
    .incbin "banims/lorm_sw1/lorm_sw1_1.4bpp.lz"

    .global BANIM_IMG_lorm_sw1_2
.align 2, 0
BANIM_IMG_lorm_sw1_2: @ 0x086DA360
    .incbin "banims/lorm_sw1/lorm_sw1_2.4bpp.lz"

    .global BANIM_IMG_lorm_sw1_3
.align 2, 0
BANIM_IMG_lorm_sw1_3: @ 0x086DB1DC
    .incbin "banims/lorm_sw1/lorm_sw1_3.4bpp.lz"

    .global BANIM_IMG_lorm_sw1_4
.align 2, 0
BANIM_IMG_lorm_sw1_4: @ 0x086DC2BC
    .incbin "banims/lorm_sw1/lorm_sw1_4.4bpp.lz"

    .global BANIM_PAL_lorm_sw1
.align 2, 0
BANIM_PAL_lorm_sw1: @ 0x086DD050
    .incbin "banims/lorm_sw1/lorm_sw1.agbpal.lz"

    .global BANIM_OAMR_lorm_sw1
.align 2, 0
BANIM_OAMR_lorm_sw1: @ 0x086DD764
    .incbin "banims/lorm_sw1/lorm_sw1.oam.oamr.bin.lz"

    .global BANIM_IMG_sagf_mg1_0
.align 2, 0
BANIM_IMG_sagf_mg1_0: @ 0x086DE248
    .incbin "banims/sagf_mg1/sagf_mg1_0.4bpp.lz"

    .global BANIM_IMG_sagf_mg1_1
.align 2, 0
BANIM_IMG_sagf_mg1_1: @ 0x086DF0C0
    .incbin "banims/sagf_mg1/sagf_mg1_1.4bpp.lz"

    .global BANIM_IMG_sagf_mg1_2
.align 2, 0
BANIM_IMG_sagf_mg1_2: @ 0x086DFF20
    .incbin "banims/sagf_mg1/sagf_mg1_2.4bpp.lz"

    .global BANIM_IMG_sagf_mg1_3
.align 2, 0
BANIM_IMG_sagf_mg1_3: @ 0x086E0E2C
    .incbin "banims/sagf_mg1/sagf_mg1_3.4bpp.lz"

    .global BANIM_PAL_sagf_mg1
.align 2, 0
BANIM_PAL_sagf_mg1: @ 0x086E19A8
    .incbin "banims/sagf_mg1/sagf_mg1.agbpal.lz"

    .global BANIM_OAMR_sagf_mg1
.align 2, 0
BANIM_OAMR_sagf_mg1: @ 0x086E1FAC
    .incbin "banims/sagf_mg1/sagf_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_solm_sp1_0
.align 2, 0
BANIM_IMG_solm_sp1_0: @ 0x086E28B4
    .incbin "banims/solm_sp1/solm_sp1_0.4bpp.lz"

    .global BANIM_IMG_solm_sp1_1
.align 2, 0
BANIM_IMG_solm_sp1_1: @ 0x086E394C
    .incbin "banims/solm_sp1/solm_sp1_1.4bpp.lz"

    .global BANIM_IMG_solm_sp1_2_0
.align 2, 0
BANIM_IMG_solm_sp1_2_0: @ 0x086E4B04
    .incbin "banims/solm_sp1/solm_sp1_2_0.4bpp.lz"

    .global BANIM_PAL_solm_sp1
.align 2, 0
BANIM_PAL_solm_sp1: @ 0x086E5238
    .incbin "banims/solm_sp1/solm_sp1.agbpal.lz"

    .global BANIM_OAMR_solm_sp1
.align 2, 0
BANIM_OAMR_solm_sp1: @ 0x086E586C
    .incbin "banims/solm_sp1/solm_sp1.oam.oamr.bin.lz"

    .global BANIM_IMG_drum_mg1_0
.align 2, 0
BANIM_IMG_drum_mg1_0: @ 0x086E60BC
    .incbin "banims/drum_mg1/drum_mg1_0.4bpp.lz"

    .global BANIM_IMG_drum_mg1_1
.align 2, 0
BANIM_IMG_drum_mg1_1: @ 0x086E6CCC
    .incbin "banims/drum_mg1/drum_mg1_1.4bpp.lz"

    .global BANIM_IMG_drum_mg1_2
.align 2, 0
BANIM_IMG_drum_mg1_2: @ 0x086E79FC
    .incbin "banims/drum_mg1/drum_mg1_2.4bpp.lz"

    .global BANIM_IMG_drum_mg1_3
.align 2, 0
BANIM_IMG_drum_mg1_3: @ 0x086E85B8
    .incbin "banims/drum_mg1/drum_mg1_3.4bpp.lz"

    .global BANIM_PAL_drum_mg1
.align 2, 0
BANIM_PAL_drum_mg1: @ 0x086E9030
    .incbin "banims/drum_mg1/drum_mg1.agbpal.lz"

    .global BANIM_OAMR_drum_mg1
.align 2, 0
BANIM_OAMR_drum_mg1: @ 0x086E9550
    .incbin "banims/drum_mg1/drum_mg1.oam.oamr.bin.lz"

    .global BANIM_PAL_lorm_sw1_2
.align 2, 0
BANIM_PAL_lorm_sw1_2: @ 0x086E9D1C
    .incbin "banims/lorm_sw1/lorm_sw1.agbpal.lz"

    .global BANIM_OAMR_lorm_sw1_2
.align 2, 0
BANIM_OAMR_lorm_sw1_2: @ 0x086E9E04
    .incbin "banims/lorm_sw1/lorm_sw1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_bram_sw1_0
.align 2, 0
BANIM_IMG_bram_sw1_0: @ 0x086E9F7C
    .incbin "banims/bram_sw1/bram_sw1_0.4bpp.lz"

    .global BANIM_IMG_bram_sw1_1
.align 2, 0
BANIM_IMG_bram_sw1_1: @ 0x086EB07C
    .incbin "banims/bram_sw1/bram_sw1_1.4bpp.lz"

    .global BANIM_IMG_bram_sw1_2
.align 2, 0
BANIM_IMG_bram_sw1_2: @ 0x086EC4E4
    .incbin "banims/bram_sw1/bram_sw1_2.4bpp.lz"

    .global BANIM_IMG_bram_sw1_3
.align 2, 0
BANIM_IMG_bram_sw1_3: @ 0x086ED614
    .incbin "banims/bram_sw1/bram_sw1_3.4bpp.lz"

    .global BANIM_PAL_bram_sw1
.align 2, 0
BANIM_PAL_bram_sw1: @ 0x086EE7E8
    .incbin "banims/bram_sw1/bram_sw1.agbpal.lz"

    .global BANIM_OAMR_bram_sw1
.align 2, 0
BANIM_OAMR_bram_sw1: @ 0x086EFDB0
    .incbin "banims/bram_sw1/bram_sw1.oam.oamr.bin.lz"

    .global BANIM_IMG_danf_no1_0
.align 2, 0
BANIM_IMG_danf_no1_0: @ 0x086F1AE4
    .incbin "banims/danf_no1/danf_no1_0.4bpp.lz"

    .global BANIM_IMG_danf_no1_1
.align 2, 0
BANIM_IMG_danf_no1_1: @ 0x086F2C28
    .incbin "banims/danf_no1/danf_no1_1.4bpp.lz"

    .global BANIM_PAL_danf_no1
.align 2, 0
BANIM_PAL_danf_no1: @ 0x086F3AC4
    .incbin "banims/danf_no1/danf_no1.agbpal.lz"

    .global BANIM_OAMR_danf_no1
.align 2, 0
BANIM_OAMR_danf_no1: @ 0x086F3F80
    .incbin "banims/danf_no1/danf_no1.oam.oamr.bin.lz"

    .global BANIM_IMG_brdm_mg1_0
.align 2, 0
BANIM_IMG_brdm_mg1_0: @ 0x086F4620
    .incbin "banims/brdm_mg1/brdm_mg1_0.4bpp.lz"

    .global BANIM_IMG_brdm_mg1_1
.align 2, 0
BANIM_IMG_brdm_mg1_1: @ 0x086F5268
    .incbin "banims/brdm_mg1/brdm_mg1_1.4bpp.lz"

    .global BANIM_PAL_brdm_mg1
.align 2, 0
BANIM_PAL_brdm_mg1: @ 0x086F5938
    .incbin "banims/brdm_mg1/brdm_mg1.agbpal.lz"

    .global BANIM_OAMR_brdm_mg1
.align 2, 0
BANIM_OAMR_brdm_mg1: @ 0x086F5BC8
    .incbin "banims/brdm_mg1/brdm_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_prif_mg1_0
.align 2, 0
BANIM_IMG_prif_mg1_0: @ 0x086F60A8
    .incbin "banims/prif_mg1/prif_mg1_0.4bpp.lz"

    .global BANIM_PAL_prif_mg1
.align 2, 0
BANIM_PAL_prif_mg1: @ 0x086F6A98
    .incbin "banims/prif_mg1/prif_mg1.agbpal.lz"

    .global BANIM_OAMR_prif_mg1
.align 2, 0
BANIM_OAMR_prif_mg1: @ 0x086F6C60
    .incbin "banims/prif_mg1/prif_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_prim_mg1_0
.align 2, 0
BANIM_IMG_prim_mg1_0: @ 0x086F6F04
    .incbin "banims/prim_mg1/prim_mg1_0.4bpp.lz"

    .global BANIM_PAL_prim_mg1
.align 2, 0
BANIM_PAL_prim_mg1: @ 0x086F79CC
    .incbin "banims/prim_mg1/prim_mg1.agbpal.lz"

    .global BANIM_OAMR_prim_mg1
.align 2, 0
BANIM_OAMR_prim_mg1: @ 0x086F7B94
    .incbin "banims/prim_mg1/prim_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_pakm_sw1_0
.align 2, 0
BANIM_IMG_pakm_sw1_0: @ 0x086F7E38
    .incbin "banims/pakm_sw1/pakm_sw1_0.4bpp.lz"

    .global BANIM_IMG_pakm_sw1_1
.align 2, 0
BANIM_IMG_pakm_sw1_1: @ 0x086F92F4
    .incbin "banims/pakm_sw1/pakm_sw1_1.4bpp.lz"

    .global BANIM_IMG_pakm_sw1_2
.align 2, 0
BANIM_IMG_pakm_sw1_2: @ 0x086FA674
    .incbin "banims/pakm_sw1/pakm_sw1_2.4bpp.lz"

    .global BANIM_IMG_pakm_sw1_3
.align 2, 0
BANIM_IMG_pakm_sw1_3: @ 0x086FBB6C
    .incbin "banims/pakm_sw1/pakm_sw1_3.4bpp.lz"

    .global BANIM_IMG_pakm_sw1_4
.align 2, 0
BANIM_IMG_pakm_sw1_4: @ 0x086FD07C
    .incbin "banims/pakm_sw1/pakm_sw1_4.4bpp.lz"

    .global BANIM_IMG_pakm_sw1_5
.align 2, 0
BANIM_IMG_pakm_sw1_5: @ 0x086FE2F4
    .incbin "banims/pakm_sw1/pakm_sw1_5.4bpp.lz"

    .global BANIM_IMG_pakm_sw1_6
.align 2, 0
BANIM_IMG_pakm_sw1_6: @ 0x086FF4B8
    .incbin "banims/pakm_sw1/pakm_sw1_6.4bpp.lz"

    .global BANIM_PAL_pakm_sw1
.align 2, 0
BANIM_PAL_pakm_sw1: @ 0x087006D0
    .incbin "banims/pakm_sw1/pakm_sw1.agbpal.lz"

    .global BANIM_OAMR_pakm_sw1
.align 2, 0
BANIM_OAMR_pakm_sw1: @ 0x08701858
    .incbin "banims/pakm_sw1/pakm_sw1.oam.oamr.bin.lz"

    .global BANIM_IMG_nomm_ar1_0
.align 2, 0
BANIM_IMG_nomm_ar1_0: @ 0x08702E30
    .incbin "banims/nomm_ar1/nomm_ar1_0.4bpp.lz"

    .global BANIM_IMG_nomm_ar1_1
.align 2, 0
BANIM_IMG_nomm_ar1_1: @ 0x08703BF4
    .incbin "banims/nomm_ar1/nomm_ar1_1.4bpp.lz"

    .global BANIM_IMG_nomm_ar1_2
.align 2, 0
BANIM_IMG_nomm_ar1_2: @ 0x087048E8
    .incbin "banims/nomm_ar1/nomm_ar1_2.4bpp.lz"

    .global BANIM_PAL_nomm_ar1
.align 2, 0
BANIM_PAL_nomm_ar1: @ 0x08705554
    .incbin "banims/nomm_ar1/nomm_ar1.agbpal.lz"

    .global BANIM_OAMR_nomm_ar1
.align 2, 0
BANIM_OAMR_nomm_ar1: @ 0x08705A54
    .incbin "banims/nomm_ar1/nomm_ar1.oam.oamr.bin.lz"

    .global BANIM_PAL_nomm_ar1_2
.align 2, 0
BANIM_PAL_nomm_ar1_2: @ 0x087061C8
    .incbin "banims/nomm_ar1/nomm_ar1.agbpal.lz"

    .global BANIM_OAMR_nomm_ar1_2
.align 2, 0
BANIM_OAMR_nomm_ar1_2: @ 0x0870631C
    .incbin "banims/nomm_ar1/nomm_ar1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_nomf_ar1_0
.align 2, 0
BANIM_IMG_nomf_ar1_0: @ 0x087064E0
    .incbin "banims/nomf_ar1/nomf_ar1_0.4bpp.lz"

    .global BANIM_IMG_nomf_ar1_1
.align 2, 0
BANIM_IMG_nomf_ar1_1: @ 0x08707260
    .incbin "banims/nomf_ar1/nomf_ar1_1.4bpp.lz"

    .global BANIM_IMG_nomf_ar1_2
.align 2, 0
BANIM_IMG_nomf_ar1_2: @ 0x08707F14
    .incbin "banims/nomf_ar1/nomf_ar1_2.4bpp.lz"

    .global BANIM_PAL_nomf_ar1
.align 2, 0
BANIM_PAL_nomf_ar1: @ 0x08708B5C
    .incbin "banims/nomf_ar1/nomf_ar1.agbpal.lz"

    .global BANIM_OAMR_nomf_ar1
.align 2, 0
BANIM_OAMR_nomf_ar1: @ 0x0870904C
    .incbin "banims/nomf_ar1/nomf_ar1.oam.oamr.bin.lz"

    .global BANIM_PAL_nomf_ar1_2
.align 2, 0
BANIM_PAL_nomf_ar1_2: @ 0x087097C0
    .incbin "banims/nomf_ar1/nomf_ar1.agbpal.lz"

    .global BANIM_OAMR_nomf_ar1_2
.align 2, 0
BANIM_OAMR_nomf_ar1_2: @ 0x08709904
    .incbin "banims/nomf_ar1/nomf_ar1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_armm_sp1_2_0
.align 2, 0
BANIM_IMG_armm_sp1_2_0: @ 0x08709E98
    .incbin "banims/armm_sp1/armm_sp1_2_0.4bpp.lz"

    .global BANIM_PAL_armm_sp1_2
.align 2, 0
BANIM_PAL_armm_sp1_2: @ 0x0870AEE0
    .incbin "banims/armm_sp1/armm_sp1.agbpal.lz"

    .global BANIM_OAMR_armm_sp1_2
.align 2, 0
BANIM_OAMR_armm_sp1_2: @ 0x0870AFD4
    .incbin "banims/armm_sp1/armm_sp1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_prif_mg1_2
.align 2, 0
BANIM_PAL_prif_mg1_2: @ 0x0870B140
    .incbin "banims/prif_mg1/prif_mg1.agbpal.lz"

    .global BANIM_OAMR_prif_mg1_2
.align 2, 0
BANIM_OAMR_prif_mg1_2: @ 0x0870B22C
    .incbin "banims/prif_mg1/prif_mg1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_prim_mg1_2
.align 2, 0
BANIM_PAL_prim_mg1_2: @ 0x0870B384
    .incbin "banims/prim_mg1/prim_mg1.agbpal.lz"

    .global BANIM_OAMR_prim_mg1_2
.align 2, 0
BANIM_OAMR_prim_mg1_2: @ 0x0870B470
    .incbin "banims/prim_mg1/prim_mg1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_figm_ax1_0
.align 2, 0
BANIM_IMG_figm_ax1_0: @ 0x0870B5C8
    .incbin "banims/figm_ax1/figm_ax1_0.4bpp.lz"

    .global BANIM_IMG_figm_ax1_1
.align 2, 0
BANIM_IMG_figm_ax1_1: @ 0x0870C850
    .incbin "banims/figm_ax1/figm_ax1_1.4bpp.lz"

    .global BANIM_IMG_figm_ax1_2
.align 2, 0
BANIM_IMG_figm_ax1_2: @ 0x0870D800
    .incbin "banims/figm_ax1/figm_ax1_2.4bpp.lz"

    .global BANIM_IMG_figm_ax1_3
.align 2, 0
BANIM_IMG_figm_ax1_3: @ 0x0870E9D0
    .incbin "banims/figm_ax1/figm_ax1_3.4bpp.lz"

    .global BANIM_PAL_figm_ax1
.align 2, 0
BANIM_PAL_figm_ax1: @ 0x0870FABC
    .incbin "banims/figm_ax1/figm_ax1.agbpal.lz"

    .global BANIM_OAMR_figm_ax1
.align 2, 0
BANIM_OAMR_figm_ax1: @ 0x08710474
    .incbin "banims/figm_ax1/figm_ax1.oam.oamr.bin.lz"

    .global BANIM_PAL_figm_ax1_2
.align 2, 0
BANIM_PAL_figm_ax1_2: @ 0x087110D8
    .incbin "banims/figm_ax1/figm_ax1.agbpal.lz"

    .global BANIM_OAMR_figm_ax1_2
.align 2, 0
BANIM_OAMR_figm_ax1_2: @ 0x087111F0
    .incbin "banims/figm_ax1/figm_ax1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_bism_mg1_0
.align 2, 0
BANIM_IMG_bism_mg1_0: @ 0x08711368
    .incbin "banims/bism_mg1/bism_mg1_0.4bpp.lz"

    .global BANIM_IMG_bism_mg1_1
.align 2, 0
BANIM_IMG_bism_mg1_1: @ 0x08712454
    .incbin "banims/bism_mg1/bism_mg1_1.4bpp.lz"

    .global BANIM_PAL_bism_mg1
.align 2, 0
BANIM_PAL_bism_mg1: @ 0x08712FF8
    .incbin "banims/bism_mg1/bism_mg1.agbpal.lz"

    .global BANIM_OAMR_bism_mg1
.align 2, 0
BANIM_OAMR_bism_mg1: @ 0x087133AC
    .incbin "banims/bism_mg1/bism_mg1.oam.oamr.bin.lz"

    .global BANIM_PAL_bism_mg1_2
.align 2, 0
BANIM_PAL_bism_mg1_2: @ 0x087139AC
    .incbin "banims/bism_mg1/bism_mg1.agbpal.lz"

    .global BANIM_OAMR_bism_mg1_2
.align 2, 0
BANIM_OAMR_bism_mg1_2: @ 0x08713B40
    .incbin "banims/bism_mg1/bism_mg1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_bisf_mg1_0
.align 2, 0
BANIM_IMG_bisf_mg1_0: @ 0x08713D6C
    .incbin "banims/bisf_mg1/bisf_mg1_0.4bpp.lz"

    .global BANIM_IMG_bisf_mg1_1
.align 2, 0
BANIM_IMG_bisf_mg1_1: @ 0x08714DDC
    .incbin "banims/bisf_mg1/bisf_mg1_1.4bpp.lz"

    .global BANIM_PAL_bisf_mg1
.align 2, 0
BANIM_PAL_bisf_mg1: @ 0x0871590C
    .incbin "banims/bisf_mg1/bisf_mg1.agbpal.lz"

    .global BANIM_OAMR_bisf_mg1
.align 2, 0
BANIM_OAMR_bisf_mg1: @ 0x08715CC0
    .incbin "banims/bisf_mg1/bisf_mg1.oam.oamr.bin.lz"

    .global BANIM_PAL_bisf_mg1_2
.align 2, 0
BANIM_PAL_bisf_mg1_2: @ 0x087162C0
    .incbin "banims/bisf_mg1/bisf_mg1.agbpal.lz"

    .global BANIM_OAMR_bisf_mg1_2
.align 2, 0
BANIM_OAMR_bisf_mg1_2: @ 0x08716454
    .incbin "banims/bisf_mg1/bisf_mg1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_mamm_no1_0
.align 2, 0
BANIM_IMG_mamm_no1_0: @ 0x08716680
    .incbin "banims/mamm_no1/mamm_no1_0.4bpp.lz"

    .global BANIM_PAL_mamm_no1
.align 2, 0
BANIM_PAL_mamm_no1: @ 0x08716DA4
    .incbin "banims/mamm_no1/mamm_no1.agbpal.lz"

    .global BANIM_OAMR_mamm_no1
.align 2, 0
BANIM_OAMR_mamm_no1: @ 0x08716E64
    .incbin "banims/mamm_no1/mamm_no1.oam.oamr.bin.lz"

    .global BANIM_IMG_mamf_no1_0
.align 2, 0
BANIM_IMG_mamf_no1_0: @ 0x08717C38
    .incbin "banims/mamf_no1/mamf_no1_0.4bpp.lz"

    .global BANIM_PAL_mamf_no1
.align 2, 0
BANIM_PAL_mamf_no1: @ 0x087189DC
    .incbin "banims/mamf_no1/mamf_no1.agbpal.lz"

    .global BANIM_OAMR_mamf_no1
.align 2, 0
BANIM_OAMR_mamf_no1: @ 0x08718C0C
    .incbin "banims/mamf_no1/mamf_no1.oam.oamr.bin.lz"

    .global BANIM_PAL_banm_ax1_2
.align 2, 0
BANIM_PAL_banm_ax1_2: @ 0x08718EF8
    .incbin "banims/banm_ax1/banm_ax1.agbpal.lz"

    .global BANIM_OAMR_banm_ax1_2
.align 2, 0
BANIM_OAMR_banm_ax1_2: @ 0x08718FCC
    .incbin "banims/banm_ax1/banm_ax1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_berm_ax1_2_0
.align 2, 0
BANIM_IMG_berm_ax1_2_0: @ 0x08719134
    .incbin "banims/berm_ax1/berm_ax1_2_0.4bpp.lz"

    .global BANIM_PAL_berm_ax1_2
.align 2, 0
BANIM_PAL_berm_ax1_2: @ 0x08719DC8
    .incbin "banims/berm_ax1/berm_ax1.agbpal.lz"

    .global BANIM_OAMR_berm_ax1_2
.align 2, 0
BANIM_OAMR_berm_ax1_2: @ 0x08719EB8
    .incbin "banims/berm_ax1/berm_ax1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_sham_mg1_0
.align 2, 0
BANIM_IMG_sham_mg1_0: @ 0x0871A03C
    .incbin "banims/sham_mg1/sham_mg1_0.4bpp.lz"

    .global BANIM_IMG_sham_mg1_1
.align 2, 0
BANIM_IMG_sham_mg1_1: @ 0x0871AC68
    .incbin "banims/sham_mg1/sham_mg1_1.4bpp.lz"

    .global BANIM_IMG_sham_mg1_2
.align 2, 0
BANIM_IMG_sham_mg1_2: @ 0x0871BA00
    .incbin "banims/sham_mg1/sham_mg1_2.4bpp.lz"

    .global BANIM_IMG_sham_mg1_3
.align 2, 0
BANIM_IMG_sham_mg1_3: @ 0x0871C5A8
    .incbin "banims/sham_mg1/sham_mg1_3.4bpp.lz"

    .global BANIM_PAL_sham_mg1
.align 2, 0
BANIM_PAL_sham_mg1: @ 0x0871D2A8
    .incbin "banims/sham_mg1/sham_mg1.agbpal.lz"

    .global BANIM_OAMR_sham_mg1
.align 2, 0
BANIM_OAMR_sham_mg1: @ 0x0871DBF0
    .incbin "banims/sham_mg1/sham_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_shaf_mg1_0
.align 2, 0
BANIM_IMG_shaf_mg1_0: @ 0x0871EA94
    .incbin "banims/shaf_mg1/shaf_mg1_0.4bpp.lz"

    .global BANIM_IMG_shaf_mg1_1
.align 2, 0
BANIM_IMG_shaf_mg1_1: @ 0x0871F540
    .incbin "banims/shaf_mg1/shaf_mg1_1.4bpp.lz"

    .global BANIM_IMG_shaf_mg1_2
.align 2, 0
BANIM_IMG_shaf_mg1_2: @ 0x08720224
    .incbin "banims/shaf_mg1/shaf_mg1_2.4bpp.lz"

    .global BANIM_IMG_shaf_mg1_3
.align 2, 0
BANIM_IMG_shaf_mg1_3: @ 0x08720D1C
    .incbin "banims/shaf_mg1/shaf_mg1_3.4bpp.lz"

    .global BANIM_PAL_shaf_mg1
.align 2, 0
BANIM_PAL_shaf_mg1: @ 0x08721994
    .incbin "banims/shaf_mg1/shaf_mg1.agbpal.lz"

    .global BANIM_OAMR_shaf_mg1
.align 2, 0
BANIM_OAMR_shaf_mg1: @ 0x087222DC
    .incbin "banims/shaf_mg1/shaf_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_warm_ax1_0
.align 2, 0
BANIM_IMG_warm_ax1_0: @ 0x08723180
    .incbin "banims/warm_ax1/warm_ax1_0.4bpp.lz"

    .global BANIM_IMG_warm_ax1_1
.align 2, 0
BANIM_IMG_warm_ax1_1: @ 0x0872413C
    .incbin "banims/warm_ax1/warm_ax1_1.4bpp.lz"

    .global BANIM_IMG_warm_ax1_2
.align 2, 0
BANIM_IMG_warm_ax1_2: @ 0x08725244
    .incbin "banims/warm_ax1/warm_ax1_2.4bpp.lz"

    .global BANIM_IMG_warm_ax1_3
.align 2, 0
BANIM_IMG_warm_ax1_3: @ 0x08725F34
    .incbin "banims/warm_ax1/warm_ax1_3.4bpp.lz"

    .global BANIM_IMG_warm_ax1_4
.align 2, 0
BANIM_IMG_warm_ax1_4: @ 0x08726DD8
    .incbin "banims/warm_ax1/warm_ax1_4.4bpp.lz"

    .global BANIM_IMG_warm_ax1_5
.align 2, 0
BANIM_IMG_warm_ax1_5: @ 0x08727F18
    .incbin "banims/warm_ax1/warm_ax1_5.4bpp.lz"

    .global BANIM_IMG_warm_ax1_6
.align 2, 0
BANIM_IMG_warm_ax1_6: @ 0x08728F40
    .incbin "banims/warm_ax1/warm_ax1_6.4bpp.lz"

    .global BANIM_IMG_warm_ax1_7
.align 2, 0
BANIM_IMG_warm_ax1_7: @ 0x08729EB8
    .incbin "banims/warm_ax1/warm_ax1_7.4bpp.lz"

    .global BANIM_PAL_warm_ax1
.align 2, 0
BANIM_PAL_warm_ax1: @ 0x0872ADB0
    .incbin "banims/warm_ax1/warm_ax1.agbpal.lz"

    .global BANIM_OAMR_warm_ax1
.align 2, 0
BANIM_OAMR_warm_ax1: @ 0x0872BBF0
    .incbin "banims/warm_ax1/warm_ax1.oam.oamr.bin.lz"

    .global BANIM_PAL_warm_ax1_2
.align 2, 0
BANIM_PAL_warm_ax1_2: @ 0x0872CE54
    .incbin "banims/warm_ax1/warm_ax1.agbpal.lz"

    .global BANIM_OAMR_warm_ax1_2
.align 2, 0
BANIM_OAMR_warm_ax1_2: @ 0x0872CF38
    .incbin "banims/warm_ax1/warm_ax1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_pirm_ax1_2
.align 2, 0
BANIM_PAL_pirm_ax1_2: @ 0x0872D09C
    .incbin "banims/pirm_ax1/pirm_ax1.agbpal.lz"

    .global BANIM_OAMR_pirm_ax1_2
.align 2, 0
BANIM_OAMR_pirm_ax1_2: @ 0x0872D1A0
    .incbin "banims/pirm_ax1/pirm_ax1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_trof_ro1_0
.align 2, 0
BANIM_IMG_trof_ro1_0: @ 0x0872D334
    .incbin "banims/trof_ro1/trof_ro1_0.4bpp.lz"

    .global BANIM_IMG_trof_ro1_1
.align 2, 0
BANIM_IMG_trof_ro1_1: @ 0x0872E06C
    .incbin "banims/trof_ro1/trof_ro1_1.4bpp.lz"

    .global BANIM_IMG_trof_ro1_2
.align 2, 0
BANIM_IMG_trof_ro1_2: @ 0x0872EE24
    .incbin "banims/trof_ro1/trof_ro1_2.4bpp.lz"

    .global BANIM_PAL_trof_ro1
.align 2, 0
BANIM_PAL_trof_ro1: @ 0x0872F89C
    .incbin "banims/trof_ro1/trof_ro1.agbpal.lz"

    .global BANIM_OAMR_trof_ro1
.align 2, 0
BANIM_OAMR_trof_ro1: @ 0x0872FB64
    .incbin "banims/trof_ro1/trof_ro1.oam.oamr.bin.lz"

    .global BANIM_PAL_trof_ro1_2
.align 2, 0
BANIM_PAL_trof_ro1_2: @ 0x0872FF90
    .incbin "banims/trof_ro1/trof_ro1.agbpal.lz"

    .global BANIM_OAMR_trof_ro1_2
.align 2, 0
BANIM_OAMR_trof_ro1_2: @ 0x087300B0
    .incbin "banims/trof_ro1/trof_ro1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_valf_mg1_0
.align 2, 0
BANIM_IMG_valf_mg1_0: @ 0x0873024C
    .incbin "banims/valf_mg1/valf_mg1_0.4bpp.lz"

    .global BANIM_IMG_valf_mg1_2_1
.align 2, 0
BANIM_IMG_valf_mg1_2_1: @ 0x08730F64
    .incbin "banims/valf_mg1/valf_mg1_2_1.4bpp.lz"

    .global BANIM_IMG_valf_mg1_1
.align 2, 0
BANIM_IMG_valf_mg1_1: @ 0x08731D44
    .incbin "banims/valf_mg1/valf_mg1_1.4bpp.lz"

    .global BANIM_IMG_valf_mg1_2
.align 2, 0
BANIM_IMG_valf_mg1_2: @ 0x08732934
    .incbin "banims/valf_mg1/valf_mg1_2.4bpp.lz"

    .global BANIM_PAL_valf_mg1
.align 2, 0
BANIM_PAL_valf_mg1: @ 0x08733588
    .incbin "banims/valf_mg1/valf_mg1.agbpal.lz"

    .global BANIM_OAMR_valf_mg1
.align 2, 0
BANIM_OAMR_valf_mg1: @ 0x08733AF0
    .incbin "banims/valf_mg1/valf_mg1.oam.oamr.bin.lz"

    .global BANIM_PAL_valf_mg1_2
.align 2, 0
BANIM_PAL_valf_mg1_2: @ 0x087342F0
    .incbin "banims/valf_mg1/valf_mg1.agbpal.lz"

    .global BANIM_OAMR_valf_mg1_2
.align 2, 0
BANIM_OAMR_valf_mg1_2: @ 0x087345DC
    .incbin "banims/valf_mg1/valf_mg1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_sagm_mg1_0
.align 2, 0
BANIM_IMG_sagm_mg1_0: @ 0x08734A24
    .incbin "banims/sagm_mg1/sagm_mg1_0.4bpp.lz"

    .global BANIM_IMG_sagm_mg1_1
.align 2, 0
BANIM_IMG_sagm_mg1_1: @ 0x08735840
    .incbin "banims/sagm_mg1/sagm_mg1_1.4bpp.lz"

    .global BANIM_IMG_sagm_mg1_2
.align 2, 0
BANIM_IMG_sagm_mg1_2: @ 0x08736408
    .incbin "banims/sagm_mg1/sagm_mg1_2.4bpp.lz"

    .global BANIM_IMG_sagm_mg1_3
.align 2, 0
BANIM_IMG_sagm_mg1_3: @ 0x0873731C
    .incbin "banims/sagm_mg1/sagm_mg1_3.4bpp.lz"

    .global BANIM_PAL_sagm_mg1
.align 2, 0
BANIM_PAL_sagm_mg1: @ 0x08737D78
    .incbin "banims/sagm_mg1/sagm_mg1.agbpal.lz"

    .global BANIM_OAMR_sagm_mg1
.align 2, 0
BANIM_OAMR_sagm_mg1: @ 0x0873837C
    .incbin "banims/sagm_mg1/sagm_mg1.oam.oamr.bin.lz"

    .global BANIM_PAL_bram_sw1_2
.align 2, 0
BANIM_PAL_bram_sw1_2: @ 0x08738C84
    .incbin "banims/bram_sw1/bram_sw1.agbpal.lz"

    .global BANIM_OAMR_bram_sw1_2
.align 2, 0
BANIM_OAMR_bram_sw1_2: @ 0x08738D94
    .incbin "banims/bram_sw1/bram_sw1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_pekf_sp1_0
.align 2, 0
BANIM_IMG_pekf_sp1_0: @ 0x08738F3C
    .incbin "banims/pekf_sp1/pekf_sp1_0.4bpp.lz"

    .global BANIM_IMG_pekf_sp1_1
.align 2, 0
BANIM_IMG_pekf_sp1_1: @ 0x0873A224
    .incbin "banims/pekf_sp1/pekf_sp1_1.4bpp.lz"

    .global BANIM_IMG_pekf_sp1_2
.align 2, 0
BANIM_IMG_pekf_sp1_2: @ 0x0873B2C4
    .incbin "banims/pekf_sp1/pekf_sp1_2.4bpp.lz"

    .global BANIM_IMG_pekf_sp1_3
.align 2, 0
BANIM_IMG_pekf_sp1_3: @ 0x0873C2E0
    .incbin "banims/pekf_sp1/pekf_sp1_3.4bpp.lz"

    .global BANIM_IMG_pekf_sp1_4
.align 2, 0
BANIM_IMG_pekf_sp1_4: @ 0x0873D59C
    .incbin "banims/pekf_sp1/pekf_sp1_4.4bpp.lz"

    .global BANIM_IMG_pekf_sp1_5
.align 2, 0
BANIM_IMG_pekf_sp1_5: @ 0x0873E650
    .incbin "banims/pekf_sp1/pekf_sp1_5.4bpp.lz"

    .global BANIM_IMG_pekf_sp1_6
.align 2, 0
BANIM_IMG_pekf_sp1_6: @ 0x0873F1C8
    .incbin "banims/pekf_sp1/pekf_sp1_6.4bpp.lz"

    .global BANIM_IMG_pekf_sp1_7
.align 2, 0
BANIM_IMG_pekf_sp1_7: @ 0x0873F598
    .incbin "banims/pekf_sp1/pekf_sp1_7.4bpp.lz"

    .global BANIM_PAL_pekf_sp1
.align 2, 0
BANIM_PAL_pekf_sp1: @ 0x0873F968
    .incbin "banims/pekf_sp1/pekf_sp1.agbpal.lz"

    .global BANIM_OAMR_pekf_sp1
.align 2, 0
BANIM_OAMR_pekf_sp1: @ 0x08740C00
    .incbin "banims/pekf_sp1/pekf_sp1.oam.oamr.bin.lz"

    .global BANIM_PAL_pekf_sp1_2
.align 2, 0
BANIM_PAL_pekf_sp1_2: @ 0x087421D0
    .incbin "banims/pekf_sp1/pekf_sp1.agbpal.lz"

    .global BANIM_OAMR_pekf_sp1_2
.align 2, 0
BANIM_OAMR_pekf_sp1_2: @ 0x08742410
    .incbin "banims/pekf_sp1/pekf_sp1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_thim_sw1_0
.align 2, 0
BANIM_IMG_thim_sw1_0: @ 0x087426D0
    .incbin "banims/thim_sw1/thim_sw1_0.4bpp.lz"

    .global BANIM_IMG_thim_sw1_1
.align 2, 0
BANIM_IMG_thim_sw1_1: @ 0x0874366C
    .incbin "banims/thim_sw1/thim_sw1_1.4bpp.lz"

    .global BANIM_IMG_thim_sw1_2
.align 2, 0
BANIM_IMG_thim_sw1_2: @ 0x087443E4
    .incbin "banims/thim_sw1/thim_sw1_2.4bpp.lz"

    .global BANIM_PAL_thim_sw1
.align 2, 0
BANIM_PAL_thim_sw1: @ 0x087447B4
    .incbin "banims/thim_sw1/thim_sw1.agbpal.lz"

    .global BANIM_OAMR_thim_sw1
.align 2, 0
BANIM_OAMR_thim_sw1: @ 0x08744CEC
    .incbin "banims/thim_sw1/thim_sw1.oam.oamr.bin.lz"

    .global BANIM_PAL_thim_sw1_2
.align 2, 0
BANIM_PAL_thim_sw1_2: @ 0x087454CC
    .incbin "banims/thim_sw1/thim_sw1.agbpal.lz"

    .global BANIM_OAMR_thim_sw1_2
.align 2, 0
BANIM_OAMR_thim_sw1_2: @ 0x087455F0
    .incbin "banims/thim_sw1/thim_sw1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_thif_sw1_0
.align 2, 0
BANIM_IMG_thif_sw1_0: @ 0x0874579C
    .incbin "banims/thif_sw1/thif_sw1_0.4bpp.lz"

    .global BANIM_IMG_thif_sw1_1
.align 2, 0
BANIM_IMG_thif_sw1_1: @ 0x087467B8
    .incbin "banims/thif_sw1/thif_sw1_1.4bpp.lz"

    .global BANIM_IMG_thif_sw1_2
.align 2, 0
BANIM_IMG_thif_sw1_2: @ 0x0874753C
    .incbin "banims/thif_sw1/thif_sw1_2.4bpp.lz"

    .global BANIM_PAL_thif_sw1
.align 2, 0
BANIM_PAL_thif_sw1: @ 0x0874790C
    .incbin "banims/thif_sw1/thif_sw1.agbpal.lz"

    .global BANIM_OAMR_thif_sw1
.align 2, 0
BANIM_OAMR_thif_sw1: @ 0x08747E44
    .incbin "banims/thif_sw1/thif_sw1.oam.oamr.bin.lz"

    .global BANIM_PAL_thif_sw1_2
.align 2, 0
BANIM_PAL_thif_sw1_2: @ 0x08748624
    .incbin "banims/thif_sw1/thif_sw1.agbpal.lz"

    .global BANIM_OAMR_thif_sw1_2
.align 2, 0
BANIM_OAMR_thif_sw1_2: @ 0x08748748
    .incbin "banims/thif_sw1/thif_sw1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_braf_sw1_0
.align 2, 0
BANIM_IMG_braf_sw1_0: @ 0x087488F4
    .incbin "banims/braf_sw1/braf_sw1_0.4bpp.lz"

    .global BANIM_IMG_braf_sw1_1
.align 2, 0
BANIM_IMG_braf_sw1_1: @ 0x0874996C
    .incbin "banims/braf_sw1/braf_sw1_1.4bpp.lz"

    .global BANIM_IMG_braf_sw1_2
.align 2, 0
BANIM_IMG_braf_sw1_2: @ 0x0874ACCC
    .incbin "banims/braf_sw1/braf_sw1_2.4bpp.lz"

    .global BANIM_IMG_braf_sw1_3
.align 2, 0
BANIM_IMG_braf_sw1_3: @ 0x0874BD70
    .incbin "banims/braf_sw1/braf_sw1_3.4bpp.lz"

    .global BANIM_PAL_braf_sw1
.align 2, 0
BANIM_PAL_braf_sw1: @ 0x0874CED4
    .incbin "banims/braf_sw1/braf_sw1.agbpal.lz"

    .global BANIM_OAMR_braf_sw1
.align 2, 0
BANIM_OAMR_braf_sw1: @ 0x0874E49C
    .incbin "banims/braf_sw1/braf_sw1.oam.oamr.bin.lz"

    .global BANIM_PAL_braf_sw1_2
.align 2, 0
BANIM_PAL_braf_sw1_2: @ 0x087501D0
    .incbin "banims/braf_sw1/braf_sw1.agbpal.lz"

    .global BANIM_OAMR_braf_sw1_2
.align 2, 0
BANIM_OAMR_braf_sw1_2: @ 0x087502E0
    .incbin "banims/braf_sw1/braf_sw1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_myrm_sw1_0
.align 2, 0
BANIM_IMG_myrm_sw1_0: @ 0x08750488
    .incbin "banims/myrm_sw1/myrm_sw1_0.4bpp.lz"

    .global BANIM_IMG_myrm_sw1_1
.align 2, 0
BANIM_IMG_myrm_sw1_1: @ 0x08751520
    .incbin "banims/myrm_sw1/myrm_sw1_1.4bpp.lz"

    .global BANIM_IMG_myrm_sw1_2
.align 2, 0
BANIM_IMG_myrm_sw1_2: @ 0x0875260C
    .incbin "banims/myrm_sw1/myrm_sw1_2.4bpp.lz"

    .global BANIM_IMG_myrm_sw1_3
.align 2, 0
BANIM_IMG_myrm_sw1_3: @ 0x087535CC
    .incbin "banims/myrm_sw1/myrm_sw1_3.4bpp.lz"

    .global BANIM_PAL_myrm_sw1
.align 2, 0
BANIM_PAL_myrm_sw1: @ 0x08754228
    .incbin "banims/myrm_sw1/myrm_sw1.agbpal.lz"

    .global BANIM_OAMR_myrm_sw1
.align 2, 0
BANIM_OAMR_myrm_sw1: @ 0x08754E70
    .incbin "banims/myrm_sw1/myrm_sw1.oam.oamr.bin.lz"

    .global BANIM_PAL_myrm_sw1_2
.align 2, 0
BANIM_PAL_myrm_sw1_2: @ 0x08755E68
    .incbin "banims/myrm_sw1/myrm_sw1.agbpal.lz"

    .global BANIM_OAMR_myrm_sw1_2
.align 2, 0
BANIM_OAMR_myrm_sw1_2: @ 0x08755F78
    .incbin "banims/myrm_sw1/myrm_sw1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_pakm_sw1_5_4
.align 2, 0
BANIM_IMG_pakm_sw1_5_4: @ 0x0875610C
    .incbin "banims/pakm_sw1/pakm_sw1_5_4.4bpp.lz"

    .global BANIM_PAL_pakm_sw1_2
.align 2, 0
BANIM_PAL_pakm_sw1_2: @ 0x087564DC
    .incbin "banims/pakm_sw1/pakm_sw1.agbpal.lz"

    .global BANIM_OAMR_pakm_sw1_2
.align 2, 0
BANIM_OAMR_pakm_sw1_2: @ 0x08757398
    .incbin "banims/pakm_sw1/pakm_sw1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_pakm_sw1_3
.align 2, 0
BANIM_PAL_pakm_sw1_3: @ 0x0875867C
    .incbin "banims/pakm_sw1/pakm_sw1.agbpal.lz"

    .global BANIM_OAMR_pakm_sw1_3
.align 2, 0
BANIM_OAMR_pakm_sw1_3: @ 0x08759424
    .incbin "banims/pakm_sw1/pakm_sw1_3.oam.oamr.bin.lz"

    .global BANIM_PAL_pakm_sw1_4
.align 2, 0
BANIM_PAL_pakm_sw1_4: @ 0x0875A5F8
    .incbin "banims/pakm_sw1/pakm_sw1.agbpal.lz"

    .global BANIM_OAMR_pakm_sw1_4
.align 2, 0
BANIM_OAMR_pakm_sw1_4: @ 0x0875A744
    .incbin "banims/pakm_sw1/pakm_sw1_4.oam.oamr.bin.lz"

    .global BANIM_PAL_arcm_ar1_2
.align 2, 0
BANIM_PAL_arcm_ar1_2: @ 0x0875A8FC
    .incbin "banims/arcm_ar1/arcm_ar1.agbpal.lz"

    .global BANIM_OAMR_arcm_ar1_2
.align 2, 0
BANIM_OAMR_arcm_ar1_2: @ 0x0875AA30
    .incbin "banims/arcm_ar1/arcm_ar1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_arcf_ar1_2
.align 2, 0
BANIM_PAL_arcf_ar1_2: @ 0x0875ABB0
    .incbin "banims/arcf_ar1/arcf_ar1.agbpal.lz"

    .global BANIM_OAMR_arcf_ar1_2
.align 2, 0
BANIM_OAMR_arcf_ar1_2: @ 0x0875ACE4
    .incbin "banims/arcf_ar1/arcf_ar1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_solm_sp1_2
.align 2, 0
BANIM_PAL_solm_sp1_2: @ 0x0875AE64
    .incbin "banims/solm_sp1/solm_sp1.agbpal.lz"

    .global BANIM_OAMR_solm_sp1_2
.align 2, 0
BANIM_OAMR_solm_sp1_2: @ 0x0875AF7C
    .incbin "banims/solm_sp1/solm_sp1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_warm_ar1_0
.align 2, 0
BANIM_IMG_warm_ar1_0: @ 0x0875B11C
    .incbin "banims/warm_ar1/warm_ar1_0.4bpp.lz"

    .global BANIM_IMG_warm_ar1_1
.align 2, 0
BANIM_IMG_warm_ar1_1: @ 0x0875C278
    .incbin "banims/warm_ar1/warm_ar1_1.4bpp.lz"

    .global BANIM_IMG_warm_ar1_2
.align 2, 0
BANIM_IMG_warm_ar1_2: @ 0x0875CD68
    .incbin "banims/warm_ar1/warm_ar1_2.4bpp.lz"

    .global BANIM_IMG_warm_ar1_3
.align 2, 0
BANIM_IMG_warm_ar1_3: @ 0x0875D8C4
    .incbin "banims/warm_ar1/warm_ar1_3.4bpp.lz"

    .global BANIM_PAL_warm_ar1
.align 2, 0
BANIM_PAL_warm_ar1: @ 0x0875E33C
    .incbin "banims/warm_ar1/warm_ar1.agbpal.lz"

    .global BANIM_OAMR_warm_ar1
.align 2, 0
BANIM_OAMR_warm_ar1: @ 0x0875E88C
    .incbin "banims/warm_ar1/warm_ar1.oam.oamr.bin.lz"

    .global BANIM_IMG_myrf_sw1_0
.align 2, 0
BANIM_IMG_myrf_sw1_0: @ 0x0875EFB8
    .incbin "banims/myrf_sw1/myrf_sw1_0.4bpp.lz"

    .global BANIM_IMG_myrf_sw1_1
.align 2, 0
BANIM_IMG_myrf_sw1_1: @ 0x0875FF48
    .incbin "banims/myrf_sw1/myrf_sw1_1.4bpp.lz"

    .global BANIM_IMG_myrf_sw1_2
.align 2, 0
BANIM_IMG_myrf_sw1_2: @ 0x08760FB4
    .incbin "banims/myrf_sw1/myrf_sw1_2.4bpp.lz"

    .global BANIM_IMG_myrf_sw1_3
.align 2, 0
BANIM_IMG_myrf_sw1_3: @ 0x08761DC4
    .incbin "banims/myrf_sw1/myrf_sw1_3.4bpp.lz"

    .global BANIM_PAL_myrf_sw1
.align 2, 0
BANIM_PAL_myrf_sw1: @ 0x0876298C
    .incbin "banims/myrf_sw1/myrf_sw1.agbpal.lz"

    .global BANIM_OAMR_myrf_sw1
.align 2, 0
BANIM_OAMR_myrf_sw1: @ 0x087635D4
    .incbin "banims/myrf_sw1/myrf_sw1.oam.oamr.bin.lz"

    .global BANIM_PAL_myrf_sw1_2
.align 2, 0
BANIM_PAL_myrf_sw1_2: @ 0x087645CC
    .incbin "banims/myrf_sw1/myrf_sw1.agbpal.lz"

    .global BANIM_OAMR_myrf_sw1_2
.align 2, 0
BANIM_OAMR_myrf_sw1_2: @ 0x087646DC
    .incbin "banims/myrf_sw1/myrf_sw1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_bram_sw1_3
.align 2, 0
BANIM_PAL_bram_sw1_3: @ 0x08764870
    .incbin "banims/bram_sw1/bram_sw1.agbpal.lz"

    .global BANIM_OAMR_bram_sw1_3
.align 2, 0
BANIM_OAMR_bram_sw1_3: @ 0x08765FCC
    .incbin "banims/bram_sw1/bram_sw1_3.oam.oamr.bin.lz"

    .global BANIM_PAL_braf_sw1_3
.align 2, 0
BANIM_PAL_braf_sw1_3: @ 0x08767FC8
    .incbin "banims/braf_sw1/braf_sw1.agbpal.lz"

    .global BANIM_OAMR_braf_sw1_3
.align 2, 0
BANIM_OAMR_braf_sw1_3: @ 0x08769724
    .incbin "banims/braf_sw1/braf_sw1_3.oam.oamr.bin.lz"

    .global BANIM_IMG_drkm_sp1_0
.align 2, 0
BANIM_IMG_drkm_sp1_0: @ 0x0876B720
    .incbin "banims/drkm_sp1/drkm_sp1_0.4bpp.lz"

    .global BANIM_IMG_drkm_sp1_1
.align 2, 0
BANIM_IMG_drkm_sp1_1: @ 0x0876CC50
    .incbin "banims/drkm_sp1/drkm_sp1_1.4bpp.lz"

    .global BANIM_IMG_drkm_sp1_2
.align 2, 0
BANIM_IMG_drkm_sp1_2: @ 0x0876DCB8
    .incbin "banims/drkm_sp1/drkm_sp1_2.4bpp.lz"

    .global BANIM_IMG_drkm_sp1_3
.align 2, 0
BANIM_IMG_drkm_sp1_3: @ 0x0876EBE0
    .incbin "banims/drkm_sp1/drkm_sp1_3.4bpp.lz"

    .global BANIM_IMG_drkm_sp1_4
.align 2, 0
BANIM_IMG_drkm_sp1_4: @ 0x0876FEBC
    .incbin "banims/drkm_sp1/drkm_sp1_4.4bpp.lz"

    .global BANIM_IMG_drkm_sp1_5
.align 2, 0
BANIM_IMG_drkm_sp1_5: @ 0x08770CC0
    .incbin "banims/drkm_sp1/drkm_sp1_5.4bpp.lz"

    .global BANIM_PAL_drkm_sp1
.align 2, 0
BANIM_PAL_drkm_sp1: @ 0x0877144C
    .incbin "banims/drkm_sp1/drkm_sp1.agbpal.lz"

    .global BANIM_OAMR_drkm_sp1
.align 2, 0
BANIM_OAMR_drkm_sp1: @ 0x08772388
    .incbin "banims/drkm_sp1/drkm_sp1.oam.oamr.bin.lz"

    .global BANIM_PAL_drkm_sp1_2
.align 2, 0
BANIM_PAL_drkm_sp1_2: @ 0x087735A4
    .incbin "banims/drkm_sp1/drkm_sp1.agbpal.lz"

    .global BANIM_OAMR_drkm_sp1_2
.align 2, 0
BANIM_OAMR_drkm_sp1_2: @ 0x087737C8
    .incbin "banims/drkm_sp1/drkm_sp1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_roym_sw1_0
.align 2, 0
BANIM_IMG_roym_sw1_0: @ 0x08773A74
    .incbin "banims/roym_sw1/roym_sw1_0.4bpp.lz"

    .global BANIM_IMG_roym_sw1_1
.align 2, 0
BANIM_IMG_roym_sw1_1: @ 0x08774C34
    .incbin "banims/roym_sw1/roym_sw1_1.4bpp.lz"

    .global BANIM_IMG_roym_sw1_2
.align 2, 0
BANIM_IMG_roym_sw1_2: @ 0x08775BA8
    .incbin "banims/roym_sw1/roym_sw1_2.4bpp.lz"

    .global BANIM_IMG_roym_sw1_3
.align 2, 0
BANIM_IMG_roym_sw1_3: @ 0x08776948
    .incbin "banims/roym_sw1/roym_sw1_3.4bpp.lz"

    .global BANIM_IMG_roym_sw1_4
.align 2, 0
BANIM_IMG_roym_sw1_4: @ 0x08777640
    .incbin "banims/roym_sw1/roym_sw1_4.4bpp.lz"

    .global BANIM_IMG_roym_sw1_5
.align 2, 0
BANIM_IMG_roym_sw1_5: @ 0x08778550
    .incbin "banims/roym_sw1/roym_sw1_5.4bpp.lz"

    .global BANIM_IMG_roym_sw1_6
.align 2, 0
BANIM_IMG_roym_sw1_6: @ 0x087796C4
    .incbin "banims/roym_sw1/roym_sw1_6.4bpp.lz"

    .global BANIM_PAL_roym_sw1
.align 2, 0
BANIM_PAL_roym_sw1: @ 0x0877A340
    .incbin "banims/roym_sw1/roym_sw1.agbpal.lz"

    .global BANIM_OAMR_roym_sw1
.align 2, 0
BANIM_OAMR_roym_sw1: @ 0x0877AE6C
    .incbin "banims/roym_sw1/roym_sw1.oam.oamr.bin.lz"

    .global BANIM_IMG_notm_sw1_0
.align 2, 0
BANIM_IMG_notm_sw1_0: @ 0x0877C0E0
    .incbin "banims/notm_sw1/notm_sw1_0.4bpp.lz"

    .global BANIM_IMG_notm_sw1_1
.align 2, 0
BANIM_IMG_notm_sw1_1: @ 0x0877D330
    .incbin "banims/notm_sw1/notm_sw1_1.4bpp.lz"

    .global BANIM_IMG_notm_sw1_2
.align 2, 0
BANIM_IMG_notm_sw1_2: @ 0x0877E610
    .incbin "banims/notm_sw1/notm_sw1_2.4bpp.lz"

    .global BANIM_IMG_notm_sw1_3
.align 2, 0
BANIM_IMG_notm_sw1_3: @ 0x0877F8F4
    .incbin "banims/notm_sw1/notm_sw1_3.4bpp.lz"

    .global BANIM_PAL_notm_sw1
.align 2, 0
BANIM_PAL_notm_sw1: @ 0x0877FF18
    .incbin "banims/notm_sw1/notm_sw1.agbpal.lz"

    .global BANIM_OAMR_notm_sw1
.align 2, 0
BANIM_OAMR_notm_sw1: @ 0x087808F0
    .incbin "banims/notm_sw1/notm_sw1.oam.oamr.bin.lz"

    .global BANIM_IMG_notf_sw1_0
.align 2, 0
BANIM_IMG_notf_sw1_0: @ 0x087815D0
    .incbin "banims/notf_sw1/notf_sw1_0.4bpp.lz"

    .global BANIM_IMG_notf_sw1_1
.align 2, 0
BANIM_IMG_notf_sw1_1: @ 0x08782830
    .incbin "banims/notf_sw1/notf_sw1_1.4bpp.lz"

    .global BANIM_IMG_notf_sw1_2
.align 2, 0
BANIM_IMG_notf_sw1_2: @ 0x08783B3C
    .incbin "banims/notf_sw1/notf_sw1_2.4bpp.lz"

    .global BANIM_IMG_notf_sw1_3
.align 2, 0
BANIM_IMG_notf_sw1_3: @ 0x08784E60
    .incbin "banims/notf_sw1/notf_sw1_3.4bpp.lz"

    .global BANIM_PAL_notf_sw1
.align 2, 0
BANIM_PAL_notf_sw1: @ 0x08785480
    .incbin "banims/notf_sw1/notf_sw1.agbpal.lz"

    .global BANIM_OAMR_notf_sw1
.align 2, 0
BANIM_OAMR_notf_sw1: @ 0x08785E58
    .incbin "banims/notf_sw1/notf_sw1.oam.oamr.bin.lz"

    .global BANIM_IMG_notm_ar1_0
.align 2, 0
BANIM_IMG_notm_ar1_0: @ 0x08786B38
    .incbin "banims/notm_ar1/notm_ar1_0.4bpp.lz"

    .global BANIM_IMG_notm_ar1_1
.align 2, 0
BANIM_IMG_notm_ar1_1: @ 0x08787CEC
    .incbin "banims/notm_ar1/notm_ar1_1.4bpp.lz"

    .global BANIM_IMG_notm_ar1_2
.align 2, 0
BANIM_IMG_notm_ar1_2: @ 0x08788BF4
    .incbin "banims/notm_ar1/notm_ar1_2.4bpp.lz"

    .global BANIM_PAL_notm_ar1
.align 2, 0
BANIM_PAL_notm_ar1: @ 0x08789E74
    .incbin "banims/notm_ar1/notm_ar1.agbpal.lz"

    .global BANIM_OAMR_notm_ar1
.align 2, 0
BANIM_OAMR_notm_ar1: @ 0x0878AAD4
    .incbin "banims/notm_ar1/notm_ar1.oam.oamr.bin.lz"

    .global BANIM_IMG_notf_ar1_0
.align 2, 0
BANIM_IMG_notf_ar1_0: @ 0x0878B978
    .incbin "banims/notf_ar1/notf_ar1_0.4bpp.lz"

    .global BANIM_IMG_notf_ar1_1
.align 2, 0
BANIM_IMG_notf_ar1_1: @ 0x0878CBD0
    .incbin "banims/notf_ar1/notf_ar1_1.4bpp.lz"

    .global BANIM_IMG_notf_ar1_2
.align 2, 0
BANIM_IMG_notf_ar1_2: @ 0x0878DAC8
    .incbin "banims/notf_ar1/notf_ar1_2.4bpp.lz"

    .global BANIM_PAL_notf_ar1
.align 2, 0
BANIM_PAL_notf_ar1: @ 0x0878ED70
    .incbin "banims/notf_ar1/notf_ar1.agbpal.lz"

    .global BANIM_OAMR_notf_ar1
.align 2, 0
BANIM_OAMR_notf_ar1: @ 0x0878FA2C
    .incbin "banims/notf_ar1/notf_ar1.oam.oamr.bin.lz"

    .global BANIM_PAL_notm_ar1_2
.align 2, 0
BANIM_PAL_notm_ar1_2: @ 0x0879093C
    .incbin "banims/notm_ar1/notm_ar1.agbpal.lz"

    .global BANIM_OAMR_notm_ar1_2
.align 2, 0
BANIM_OAMR_notm_ar1_2: @ 0x08790AC8
    .incbin "banims/notm_ar1/notm_ar1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_notf_ar1_2
.align 2, 0
BANIM_PAL_notf_ar1_2: @ 0x08790C8C
    .incbin "banims/notf_ar1/notf_ar1.agbpal.lz"

    .global BANIM_OAMR_notf_ar1_2
.align 2, 0
BANIM_OAMR_notf_ar1_2: @ 0x08790E20
    .incbin "banims/notf_ar1/notf_ar1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_fifd_mg1_0
.align 2, 0
BANIM_IMG_fifd_mg1_0: @ 0x08790FE8
    .incbin "banims/fifd_mg1/fifd_mg1_0.4bpp.lz"

    .global BANIM_PAL_fifd_mg1
.align 2, 0
BANIM_PAL_fifd_mg1: @ 0x08791B38
    .incbin "banims/fifd_mg1/fifd_mg1.agbpal.lz"

    .global BANIM_OAMR_fifd_mg1
.align 2, 0
BANIM_OAMR_fifd_mg1: @ 0x08791D08
    .incbin "banims/fifd_mg1/fifd_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_swmm_sw1_0
.align 2, 0
BANIM_IMG_swmm_sw1_0: @ 0x08792028
    .incbin "banims/swmm_sw1/swmm_sw1_0.4bpp.lz"

    .global BANIM_IMG_swmm_sw1_1
.align 2, 0
BANIM_IMG_swmm_sw1_1: @ 0x087930CC
    .incbin "banims/swmm_sw1/swmm_sw1_1.4bpp.lz"

    .global BANIM_IMG_swmm_sw1_2
.align 2, 0
BANIM_IMG_swmm_sw1_2: @ 0x08793F5C
    .incbin "banims/swmm_sw1/swmm_sw1_2.4bpp.lz"

    .global BANIM_IMG_swmm_sw1_3
.align 2, 0
BANIM_IMG_swmm_sw1_3: @ 0x087951EC
    .incbin "banims/swmm_sw1/swmm_sw1_3.4bpp.lz"

    .global BANIM_PAL_swmm_sw1
.align 2, 0
BANIM_PAL_swmm_sw1: @ 0x08795A74
    .incbin "banims/swmm_sw1/swmm_sw1.agbpal.lz"

    .global BANIM_OAMR_swmm_sw1
.align 2, 0
BANIM_OAMR_swmm_sw1: @ 0x087966B0
    .incbin "banims/swmm_sw1/swmm_sw1.oam.oamr.bin.lz"

    .global BANIM_PAL_swmm_sw1_2
.align 2, 0
BANIM_PAL_swmm_sw1_2: @ 0x0879778C
    .incbin "banims/swmm_sw1/swmm_sw1.agbpal.lz"

    .global BANIM_OAMR_swmm_sw1_2
.align 2, 0
BANIM_OAMR_swmm_sw1_2: @ 0x08797840
    .incbin "banims/swmm_sw1/swmm_sw1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_swmf_sw1_0
.align 2, 0
BANIM_IMG_swmf_sw1_0: @ 0x08797954
    .incbin "banims/swmf_sw1/swmf_sw1_0.4bpp.lz"

    .global BANIM_IMG_swmf_sw1_1
.align 2, 0
BANIM_IMG_swmf_sw1_1: @ 0x08798970
    .incbin "banims/swmf_sw1/swmf_sw1_1.4bpp.lz"

    .global BANIM_IMG_swmf_sw1_2
.align 2, 0
BANIM_IMG_swmf_sw1_2: @ 0x08799818
    .incbin "banims/swmf_sw1/swmf_sw1_2.4bpp.lz"

    .global BANIM_IMG_swmf_sw1_3
.align 2, 0
BANIM_IMG_swmf_sw1_3: @ 0x0879AA9C
    .incbin "banims/swmf_sw1/swmf_sw1_3.4bpp.lz"

    .global BANIM_PAL_swmf_sw1
.align 2, 0
BANIM_PAL_swmf_sw1: @ 0x0879B324
    .incbin "banims/swmf_sw1/swmf_sw1.agbpal.lz"

    .global BANIM_OAMR_swmf_sw1
.align 2, 0
BANIM_OAMR_swmf_sw1: @ 0x0879BF60
    .incbin "banims/swmf_sw1/swmf_sw1.oam.oamr.bin.lz"

    .global BANIM_PAL_swmf_sw1_2
.align 2, 0
BANIM_PAL_swmf_sw1_2: @ 0x0879D03C
    .incbin "banims/swmf_sw1/swmf_sw1.agbpal.lz"

    .global BANIM_OAMR_swmf_sw1_2
.align 2, 0
BANIM_OAMR_swmf_sw1_2: @ 0x0879D0F0
    .incbin "banims/swmf_sw1/swmf_sw1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_drum_mg1_2
.align 2, 0
BANIM_PAL_drum_mg1_2: @ 0x0879D204
    .incbin "banims/drum_mg1/drum_mg1.agbpal.lz"

    .global BANIM_OAMR_drum_mg1_2
.align 2, 0
BANIM_OAMR_drum_mg1_2: @ 0x0879D51C
    .incbin "banims/drum_mg1/drum_mg1_2.oam.oamr.bin.lz"

    .global BANIM_IMG_godd_mg1_0
.align 2, 0
BANIM_IMG_godd_mg1_0: @ 0x0879D9D4
    .incbin "banims/godd_mg1/godd_mg1_0.4bpp.lz"

    .global BANIM_IMG_godd_mg1_1
.align 2, 0
BANIM_IMG_godd_mg1_1: @ 0x0879EC8C
    .incbin "banims/godd_mg1/godd_mg1_1.4bpp.lz"

    .global BANIM_IMG_godd_mg1_2
.align 2, 0
BANIM_IMG_godd_mg1_2: @ 0x087A00FC
    .incbin "banims/godd_mg1/godd_mg1_2.4bpp.lz"

    .global BANIM_IMG_godd_mg1_3
.align 2, 0
BANIM_IMG_godd_mg1_3: @ 0x087A1480
    .incbin "banims/godd_mg1/godd_mg1_3.4bpp.lz"

    .global BANIM_PAL_godd_mg1
.align 2, 0
BANIM_PAL_godd_mg1: @ 0x087A21C4
    .incbin "banims/godd_mg1/godd_mg1.agbpal.lz"

    .global BANIM_OAMR_godd_mg1
.align 2, 0
BANIM_OAMR_godd_mg1: @ 0x087A2804
    .incbin "banims/godd_mg1/godd_mg1.oam.oamr.bin.lz"

    .global BANIM_PAL_pirm_ax1_3
.align 2, 0
BANIM_PAL_pirm_ax1_3: @ 0x087A2FAC
    .incbin "banims/pirm_ax1/pirm_ax1.agbpal.lz"

    .global BANIM_OAMR_pirm_ax1_3
.align 2, 0
BANIM_OAMR_pirm_ax1_3: @ 0x087A3288
    .incbin "banims/pirm_ax1/pirm_ax1_3.oam.oamr.bin.lz"

    .global BANIM_PAL_berm_ax1_3
.align 2, 0
BANIM_PAL_berm_ax1_3: @ 0x087A3670
    .incbin "banims/berm_ax1/berm_ax1.agbpal.lz"

    .global BANIM_OAMR_berm_ax1_3
.align 2, 0
BANIM_OAMR_berm_ax1_3: @ 0x087A38E8
    .incbin "banims/berm_ax1/berm_ax1_3.oam.oamr.bin.lz"

    .global BANIM_PAL_banm_ax1_3
.align 2, 0
BANIM_PAL_banm_ax1_3: @ 0x087A3C84
    .incbin "banims/banm_ax1/banm_ax1.agbpal.lz"

    .global BANIM_OAMR_banm_ax1_3
.align 2, 0
BANIM_OAMR_banm_ax1_3: @ 0x087A3EE8
    .incbin "banims/banm_ax1/banm_ax1_3.oam.oamr.bin.lz"

    .global BANIM_PAL_figm_ax1_3
.align 2, 0
BANIM_PAL_figm_ax1_3: @ 0x087A4278
    .incbin "banims/figm_ax1/figm_ax1.agbpal.lz"

    .global BANIM_OAMR_figm_ax1_3
.align 2, 0
BANIM_OAMR_figm_ax1_3: @ 0x087A4590
    .incbin "banims/figm_ax1/figm_ax1_3.oam.oamr.bin.lz"

    .global BANIM_PAL_bram_sw1_4
.align 2, 0
BANIM_PAL_bram_sw1_4: @ 0x087A49E8
    .incbin "banims/bram_sw1/bram_sw1.agbpal.lz"

    .global BANIM_OAMR_bram_sw1_4
.align 2, 0
BANIM_OAMR_bram_sw1_4: @ 0x087A4C94
    .incbin "banims/bram_sw1/bram_sw1_4.oam.oamr.bin.lz"

    .global BANIM_PAL_braf_sw1_4
.align 2, 0
BANIM_PAL_braf_sw1_4: @ 0x087A50D0
    .incbin "banims/braf_sw1/braf_sw1.agbpal.lz"

    .global BANIM_OAMR_braf_sw1_4
.align 2, 0
BANIM_OAMR_braf_sw1_4: @ 0x087A537C
    .incbin "banims/braf_sw1/braf_sw1_4.oam.oamr.bin.lz"

    .global BANIM_PAL_pakm_sw1_5
.align 2, 0
BANIM_PAL_pakm_sw1_5: @ 0x087A57B8
    .incbin "banims/pakm_sw1/pakm_sw1.agbpal.lz"

    .global BANIM_OAMR_pakm_sw1_5
.align 2, 0
BANIM_OAMR_pakm_sw1_5: @ 0x087A644C
    .incbin "banims/pakm_sw1/pakm_sw1_5.oam.oamr.bin.lz"

    .global BANIM_PAL_warm_ax1_3
.align 2, 0
BANIM_PAL_warm_ax1_3: @ 0x087A7310
    .incbin "banims/warm_ax1/warm_ax1.agbpal.lz"

    .global BANIM_OAMR_warm_ax1_3
.align 2, 0
BANIM_OAMR_warm_ax1_3: @ 0x087A7E50
    .incbin "banims/warm_ax1/warm_ax1_3.oam.oamr.bin.lz"

    .global BANIM_IMG_drmm_sp1_0
.align 2, 0
BANIM_IMG_drmm_sp1_0: @ 0x087A8B9C
    .incbin "banims/drmm_sp1/drmm_sp1_0.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_1
.align 2, 0
BANIM_IMG_drmm_sp1_1: @ 0x087A9BD4
    .incbin "banims/drmm_sp1/drmm_sp1_1.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_2
.align 2, 0
BANIM_IMG_drmm_sp1_2: @ 0x087AAD60
    .incbin "banims/drmm_sp1/drmm_sp1_2.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_3
.align 2, 0
BANIM_IMG_drmm_sp1_3: @ 0x087ABA40
    .incbin "banims/drmm_sp1/drmm_sp1_3.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_4
.align 2, 0
BANIM_IMG_drmm_sp1_4: @ 0x087ACDB0
    .incbin "banims/drmm_sp1/drmm_sp1_4.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_5
.align 2, 0
BANIM_IMG_drmm_sp1_5: @ 0x087ADDFC
    .incbin "banims/drmm_sp1/drmm_sp1_5.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_6
.align 2, 0
BANIM_IMG_drmm_sp1_6: @ 0x087AEC6C
    .incbin "banims/drmm_sp1/drmm_sp1_6.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_7
.align 2, 0
BANIM_IMG_drmm_sp1_7: @ 0x087AFEB8
    .incbin "banims/drmm_sp1/drmm_sp1_7.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_3_1
.align 2, 0
BANIM_IMG_drmm_sp1_3_1: @ 0x087B11C8
    .incbin "banims/drmm_sp1/drmm_sp1_3_1.4bpp.lz"

    .global BANIM_IMG_drmm_sp1_8
.align 2, 0
BANIM_IMG_drmm_sp1_8: @ 0x087B1F58
    .incbin "banims/drmm_sp1/drmm_sp1_8.4bpp.lz"

    .global BANIM_PAL_drmm_sp1
.align 2, 0
BANIM_PAL_drmm_sp1: @ 0x087B2ED8
    .incbin "banims/drmm_sp1/drmm_sp1.agbpal.lz"

    .global BANIM_OAMR_drmm_sp1
.align 2, 0
BANIM_OAMR_drmm_sp1: @ 0x087B483C
    .incbin "banims/drmm_sp1/drmm_sp1.oam.oamr.bin.lz"

    .global BANIM_IMG_drmm_sp1_2_9
.align 2, 0
BANIM_IMG_drmm_sp1_2_9: @ 0x087B6564
    .incbin "banims/drmm_sp1/drmm_sp1_2_9.4bpp.lz"

    .global BANIM_PAL_drmm_sp1_2
.align 2, 0
BANIM_PAL_drmm_sp1_2: @ 0x087B6F78
    .incbin "banims/drmm_sp1/drmm_sp1.agbpal.lz"

    .global BANIM_OAMR_drmm_sp1_2
.align 2, 0
BANIM_OAMR_drmm_sp1_2: @ 0x087B8B50
    .incbin "banims/drmm_sp1/drmm_sp1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_drmm_sp1_3
.align 2, 0
BANIM_PAL_drmm_sp1_3: @ 0x087BAAE0
    .incbin "banims/drmm_sp1/drmm_sp1.agbpal.lz"

    .global BANIM_OAMR_drmm_sp1_3
.align 2, 0
BANIM_OAMR_drmm_sp1_3: @ 0x087BAD40
    .incbin "banims/drmm_sp1/drmm_sp1_3.oam.oamr.bin.lz"

    .global BANIM_IMG_stam_ar1_0
.align 2, 0
BANIM_IMG_stam_ar1_0: @ 0x087BB014
    .incbin "banims/stam_ar1/stam_ar1_0.4bpp.lz"

    .global BANIM_PAL_stam_ar1
.align 2, 0
BANIM_PAL_stam_ar1: @ 0x087BBA74
    .incbin "banims/stam_ar1/stam_ar1.agbpal.lz"

    .global BANIM_OAMR_stam_ar1
.align 2, 0
BANIM_OAMR_stam_ar1: @ 0x087BBC70
    .incbin "banims/stam_ar1/stam_ar1.oam.oamr.bin.lz"

    .global BANIM_IMG_genm_al1_0
.align 2, 0
BANIM_IMG_genm_al1_0: @ 0x087BBF14
    .incbin "banims/genm_al1/genm_al1_0.4bpp.lz"

    .global BANIM_IMG_genm_al1_2_1
.align 2, 0
BANIM_IMG_genm_al1_2_1: @ 0x087BCC24
    .incbin "banims/genm_al1/genm_al1_2_1.4bpp.lz"

    .global BANIM_IMG_genm_al1_1
.align 2, 0
BANIM_IMG_genm_al1_1: @ 0x087BD944
    .incbin "banims/genm_al1/genm_al1_1.4bpp.lz"

    .global BANIM_IMG_genm_al1_2
.align 2, 0
BANIM_IMG_genm_al1_2: @ 0x087BE784
    .incbin "banims/genm_al1/genm_al1_2.4bpp.lz"

    .global BANIM_IMG_genm_al1_2_4
.align 2, 0
BANIM_IMG_genm_al1_2_4: @ 0x087BF688
    .incbin "banims/genm_al1/genm_al1_2_4.4bpp.lz"

    .global BANIM_IMG_genm_al1_3
.align 2, 0
BANIM_IMG_genm_al1_3: @ 0x087C0244
    .incbin "banims/genm_al1/genm_al1_3.4bpp.lz"

    .global BANIM_IMG_genm_al1_4
.align 2, 0
BANIM_IMG_genm_al1_4: @ 0x087C0FCC
    .incbin "banims/genm_al1/genm_al1_4.4bpp.lz"

    .global BANIM_IMG_genm_al1_2_7
.align 2, 0
BANIM_IMG_genm_al1_2_7: @ 0x087C2064
    .incbin "banims/genm_al1/genm_al1_2_7.4bpp.lz"

    .global BANIM_IMG_genm_al1_5
.align 2, 0
BANIM_IMG_genm_al1_5: @ 0x087C2DCC
    .incbin "banims/genm_al1/genm_al1_5.4bpp.lz"

    .global BANIM_PAL_genm_al1
.align 2, 0
BANIM_PAL_genm_al1: @ 0x087C3B84
    .incbin "banims/genm_al1/genm_al1.agbpal.lz"

    .global BANIM_OAMR_genm_al1
.align 2, 0
BANIM_OAMR_genm_al1: @ 0x087C3F30
    .incbin "banims/genm_al1/genm_al1.oam.oamr.bin.lz"

    .global BANIM_PAL_bism_mg1_3
.align 2, 0
BANIM_PAL_bism_mg1_3: @ 0x087C4490
    .incbin "banims/bism_mg1/bism_mg1.agbpal.lz"

    .global BANIM_OAMR_bism_mg1_3
.align 2, 0
BANIM_OAMR_bism_mg1_3: @ 0x087C4594
    .incbin "banims/bism_mg1/bism_mg1_3.oam.oamr.bin.lz"

    .global BANIM_PAL_bisf_mg1_3
.align 2, 0
BANIM_PAL_bisf_mg1_3: @ 0x087C4708
    .incbin "banims/bisf_mg1/bisf_mg1.agbpal.lz"

    .global BANIM_OAMR_bisf_mg1_3
.align 2, 0
BANIM_OAMR_bisf_mg1_3: @ 0x087C480C
    .incbin "banims/bisf_mg1/bisf_mg1_3.oam.oamr.bin.lz"

    .global BANIM_IMG_godd_he1_0
.align 2, 0
BANIM_IMG_godd_he1_0: @ 0x087C4980
    .incbin "banims/godd_he1/godd_he1_0.4bpp.lz"

    .global BANIM_IMG_godd_he1_1
.align 2, 0
BANIM_IMG_godd_he1_1: @ 0x087C54E4
    .incbin "banims/godd_he1/godd_he1_1.4bpp.lz"

    .global BANIM_IMG_godd_he1_2
.align 2, 0
BANIM_IMG_godd_he1_2: @ 0x087C63B4
    .incbin "banims/godd_he1/godd_he1_2.4bpp.lz"

    .global BANIM_IMG_godd_he1_3
.align 2, 0
BANIM_IMG_godd_he1_3: @ 0x087C7408
    .incbin "banims/godd_he1/godd_he1_3.4bpp.lz"

    .global BANIM_PAL_godd_he1
.align 2, 0
BANIM_PAL_godd_he1: @ 0x087C7D4C
    .incbin "banims/godd_he1/godd_he1.agbpal.lz"

    .global BANIM_OAMR_godd_he1
.align 2, 0
BANIM_OAMR_godd_he1: @ 0x087C81C8
    .incbin "banims/godd_he1/godd_he1.oam.oamr.bin.lz"

    .global BANIM_IMG_godd_hk1_0
.align 2, 0
BANIM_IMG_godd_hk1_0: @ 0x087C872C
    .incbin "banims/godd_hk1/godd_hk1_0.4bpp.lz"

    .global BANIM_IMG_godd_hk1_1
.align 2, 0
BANIM_IMG_godd_hk1_1: @ 0x087C97C8
    .incbin "banims/godd_hk1/godd_hk1_1.4bpp.lz"

    .global BANIM_PAL_godd_hk1
.align 2, 0
BANIM_PAL_godd_hk1: @ 0x087CA0F4
    .incbin "banims/godd_hk1/godd_hk1.agbpal.lz"

    .global BANIM_OAMR_godd_hk1
.align 2, 0
BANIM_OAMR_godd_hk1: @ 0x087CA388
    .incbin "banims/godd_hk1/godd_hk1.oam.oamr.bin.lz"

    .global BANIM_PAL_genm_al1_2
.align 2, 0
BANIM_PAL_genm_al1_2: @ 0x087CA61C
    .incbin "banims/genm_al1/genm_al1.agbpal.lz"

    .global BANIM_OAMR_genm_al1_2
.align 2, 0
BANIM_OAMR_genm_al1_2: @ 0x087CB3E0
    .incbin "banims/genm_al1/genm_al1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_genm_al1_3
.align 2, 0
BANIM_PAL_genm_al1_3: @ 0x087CC65C
    .incbin "banims/genm_al1/genm_al1.agbpal.lz"

    .global BANIM_OAMR_genm_al1_3
.align 2, 0
BANIM_OAMR_genm_al1_3: @ 0x087CCE60
    .incbin "banims/genm_al1/genm_al1_3.oam.oamr.bin.lz"

    .global BANIM_PAL_genm_al1_4
.align 2, 0
BANIM_PAL_genm_al1_4: @ 0x087CDAF4
    .incbin "banims/genm_al1/genm_al1.agbpal.lz"

    .global BANIM_OAMR_genm_al1_4
.align 2, 0
BANIM_OAMR_genm_al1_4: @ 0x087CDC0C
    .incbin "banims/genm_al1/genm_al1_4.oam.oamr.bin.lz"

    .global BANIM_IMG_druf_mg1_0
.align 2, 0
BANIM_IMG_druf_mg1_0: @ 0x087CDD90
    .incbin "banims/druf_mg1/druf_mg1_0.4bpp.lz"

    .global BANIM_IMG_druf_mg1_1
.align 2, 0
BANIM_IMG_druf_mg1_1: @ 0x087CE838
    .incbin "banims/druf_mg1/druf_mg1_1.4bpp.lz"

    .global BANIM_IMG_druf_mg1_2
.align 2, 0
BANIM_IMG_druf_mg1_2: @ 0x087CF490
    .incbin "banims/druf_mg1/druf_mg1_2.4bpp.lz"

    .global BANIM_IMG_druf_mg1_3
.align 2, 0
BANIM_IMG_druf_mg1_3: @ 0x087CFF68
    .incbin "banims/druf_mg1/druf_mg1_3.4bpp.lz"

    .global BANIM_PAL_druf_mg1
.align 2, 0
BANIM_PAL_druf_mg1: @ 0x087D08B0
    .incbin "banims/druf_mg1/druf_mg1.agbpal.lz"

    .global BANIM_OAMR_druf_mg1
.align 2, 0
BANIM_OAMR_druf_mg1: @ 0x087D0DD0
    .incbin "banims/druf_mg1/druf_mg1.oam.oamr.bin.lz"

    .global BANIM_PAL_druf_mg1_2
.align 2, 0
BANIM_PAL_druf_mg1_2: @ 0x087D159C
    .incbin "banims/druf_mg1/druf_mg1.agbpal.lz"

    .global BANIM_OAMR_druf_mg1_2
.align 2, 0
BANIM_OAMR_druf_mg1_2: @ 0x087D18B4
    .incbin "banims/druf_mg1/druf_mg1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_fakf_sp1_2
.align 2, 0
BANIM_PAL_fakf_sp1_2: @ 0x087D1D6C
    .incbin "banims/fakf_sp1/fakf_sp1.agbpal.lz"

    .global BANIM_OAMR_fakf_sp1_2
.align 2, 0
BANIM_OAMR_fakf_sp1_2: @ 0x087D3758
    .incbin "banims/fakf_sp1/fakf_sp1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_fakf_sp1_3
.align 2, 0
BANIM_PAL_fakf_sp1_3: @ 0x087D55B8
    .incbin "banims/fakf_sp1/fakf_sp1.agbpal.lz"

    .global BANIM_OAMR_fakf_sp1_3
.align 2, 0
BANIM_OAMR_fakf_sp1_3: @ 0x087D57D8
    .incbin "banims/fakf_sp1/fakf_sp1_3.oam.oamr.bin.lz"

    .global BANIM_IMG_magdd_mg1_0
.align 2, 0
BANIM_IMG_magdd_mg1_0: @ 0x087D5A78
    .incbin "banims/magdd_mg1/magdd_mg1_0.4bpp.lz"

    .global BANIM_IMG_magdd_mg1_1
.align 2, 0
BANIM_IMG_magdd_mg1_1: @ 0x087D6CD4
    .incbin "banims/magdd_mg1/magdd_mg1_1.4bpp.lz"

    .global BANIM_IMG_magdd_mg1_2
.align 2, 0
BANIM_IMG_magdd_mg1_2: @ 0x087D7D98
    .incbin "banims/magdd_mg1/magdd_mg1_2.4bpp.lz"

    .global BANIM_PAL_magdd_mg1
.align 2, 0
BANIM_PAL_magdd_mg1: @ 0x087D8A4C
    .incbin "banims/magdd_mg1/magdd_mg1.agbpal.lz"

    .global BANIM_OAMR_magdd_mg1
.align 2, 0
BANIM_OAMR_magdd_mg1: @ 0x087D97C0
    .incbin "banims/magdd_mg1/magdd_mg1.oam.oamr.bin.lz"

    .global BANIM_IMG_kinm_al1_0
.align 2, 0
BANIM_IMG_kinm_al1_0: @ 0x087DA81C
    .incbin "banims/kinm_al1/kinm_al1_0.4bpp.lz"

    .global BANIM_IMG_kinm_al1_1
.align 2, 0
BANIM_IMG_kinm_al1_1: @ 0x087DB8B4
    .incbin "banims/kinm_al1/kinm_al1_1.4bpp.lz"

    .global BANIM_IMG_kinm_al1_2
.align 2, 0
BANIM_IMG_kinm_al1_2: @ 0x087DC608
    .incbin "banims/kinm_al1/kinm_al1_2.4bpp.lz"

    .global BANIM_IMG_kinm_al1_3
.align 2, 0
BANIM_IMG_kinm_al1_3: @ 0x087DD560
    .incbin "banims/kinm_al1/kinm_al1_3.4bpp.lz"

    .global BANIM_IMG_kinm_al1_4
.align 2, 0
BANIM_IMG_kinm_al1_4: @ 0x087DE618
    .incbin "banims/kinm_al1/kinm_al1_4.4bpp.lz"

    .global BANIM_IMG_kinm_al1_5
.align 2, 0
BANIM_IMG_kinm_al1_5: @ 0x087DF434
    .incbin "banims/kinm_al1/kinm_al1_5.4bpp.lz"

    .global BANIM_IMG_kinm_al1_6
.align 2, 0
BANIM_IMG_kinm_al1_6: @ 0x087E0014
    .incbin "banims/kinm_al1/kinm_al1_6.4bpp.lz"

    .global BANIM_IMG_kinm_al1_7
.align 2, 0
BANIM_IMG_kinm_al1_7: @ 0x087E0C3C
    .incbin "banims/kinm_al1/kinm_al1_7.4bpp.lz"

    .global BANIM_IMG_kinm_al1_8
.align 2, 0
BANIM_IMG_kinm_al1_8: @ 0x087E1CF0
    .incbin "banims/kinm_al1/kinm_al1_8.4bpp.lz"

    .global BANIM_IMG_kinm_al1_9
.align 2, 0
BANIM_IMG_kinm_al1_9: @ 0x087E2F84
    .incbin "banims/kinm_al1/kinm_al1_9.4bpp.lz"

    .global BANIM_IMG_kinm_al1_10
.align 2, 0
BANIM_IMG_kinm_al1_10: @ 0x087E3DB4
    .incbin "banims/kinm_al1/kinm_al1_10.4bpp.lz"

    .global BANIM_PAL_kinm_al1
.align 2, 0
BANIM_PAL_kinm_al1: @ 0x087E4F24
    .incbin "banims/kinm_al1/kinm_al1.agbpal.lz"

    .global BANIM_OAMR_kinm_al1
.align 2, 0
BANIM_OAMR_kinm_al1: @ 0x087E67F8
    .incbin "banims/kinm_al1/kinm_al1.oam.oamr.bin.lz"

    .global BANIM_PAL_snim_ar1_2
.align 2, 0
BANIM_PAL_snim_ar1_2: @ 0x087E8B24
    .incbin "banims/snim_ar1/snim_ar1.agbpal.lz"

    .global BANIM_OAMR_snim_ar1_2
.align 2, 0
BANIM_OAMR_snim_ar1_2: @ 0x087E8C38
    .incbin "banims/snim_ar1/snim_ar1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_snif_ar1_2
.align 2, 0
BANIM_PAL_snif_ar1_2: @ 0x087E8D98
    .incbin "banims/snif_ar1/snif_ar1.agbpal.lz"

    .global BANIM_OAMR_snif_ar1_2
.align 2, 0
BANIM_OAMR_snif_ar1_2: @ 0x087E8EAC
    .incbin "banims/snif_ar1/snif_ar1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_sagm_mg1_2
.align 2, 0
BANIM_PAL_sagm_mg1_2: @ 0x087E900C
    .incbin "banims/sagm_mg1/sagm_mg1.agbpal.lz"

    .global BANIM_OAMR_sagm_mg1_2
.align 2, 0
BANIM_OAMR_sagm_mg1_2: @ 0x087E91DC
    .incbin "banims/sagm_mg1/sagm_mg1_2.oam.oamr.bin.lz"

    .global BANIM_PAL_sagf_mg1_2
.align 2, 0
BANIM_PAL_sagf_mg1_2: @ 0x087E9454
    .incbin "banims/sagf_mg1/sagf_mg1.agbpal.lz"

    .global BANIM_OAMR_sagf_mg1_2
.align 2, 0
BANIM_OAMR_sagf_mg1_2: @ 0x087E9624
    .incbin "banims/sagf_mg1/sagf_mg1_2.oam.oamr.bin.lz"
