	.section .content_data.skillsys

.align 2, 0
.global Gfx_SkillIcon_BonusMag
Gfx_SkillIcon_BonusMag:
	.incbin "contents/skillsys/SkillIcon/BonusMag.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BlowDuelist
Gfx_SkillIcon_BlowDuelist:
	.incbin "contents/skillsys/SkillIcon/BlowDuelist.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BonusHp
Gfx_SkillIcon_BonusHp:
	.incbin "contents/skillsys/SkillIcon/BonusHp.4bpp"

.align 2, 0
.global Gfx_SkillIcon_RangeBonusBow1
Gfx_SkillIcon_RangeBonusBow1:
	.incbin "contents/skillsys/SkillIcon/RangeBonusBow1.4bpp"

.align 2, 0
.global Gfx_SkillIcon_RangeBonusBMag2
Gfx_SkillIcon_RangeBonusBMag2:
	.incbin "contents/skillsys/SkillIcon/RangeBonusBMag2.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BlowFiendish
Gfx_SkillIcon_BlowFiendish:
	.incbin "contents/skillsys/SkillIcon/BlowFiendish.4bpp"

.align 2, 0
.global Gfx_SkillIcon_RangeBonusBMag1
Gfx_SkillIcon_RangeBonusBMag1:
	.incbin "contents/skillsys/SkillIcon/RangeBonusBMag1.4bpp"

.align 2, 0
.global Gfx_SkillIcon_RangeBonusBow2
Gfx_SkillIcon_RangeBonusBow2:
	.incbin "contents/skillsys/SkillIcon/RangeBonusBow2.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BlowUncanny
Gfx_SkillIcon_BlowUncanny:
	.incbin "contents/skillsys/SkillIcon/BlowUncanny.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BlowArmored
Gfx_SkillIcon_BlowArmored:
	.incbin "contents/skillsys/SkillIcon/BlowArmored.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BonusPow
Gfx_SkillIcon_BonusPow:
	.incbin "contents/skillsys/SkillIcon/BonusPow.4bpp"

.align 2, 0
.global Gfx_SkillIcon_WIP
Gfx_SkillIcon_WIP:
	.incbin "contents/skillsys/SkillIcon/WIP.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BlowWarding
Gfx_SkillIcon_BlowWarding:
	.incbin "contents/skillsys/SkillIcon/BlowWarding.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BlowDeath
Gfx_SkillIcon_BlowDeath:
	.incbin "contents/skillsys/SkillIcon/BlowDeath.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BlowDarting
Gfx_SkillIcon_BlowDarting:
	.incbin "contents/skillsys/SkillIcon/BlowDarting.4bpp"

.align 2, 0
.global Gfx_SkillIcon_BlowKilling
Gfx_SkillIcon_BlowKilling:
	.incbin "contents/skillsys/SkillIcon/BlowKilling.4bpp"
