	.section .content_data

.align 2,0
.global Tsa_StatScreenBg1Left
Tsa_StatScreenBg1Left:
	.incbin "graphics/statscreen/vanilla-remix/Tsa_StatscreenPageLeft.dmp.lz"

.align 2,0
.global Tsa_StatScreenBg1PageLong
Tsa_StatScreenBg1PageLong:
	.incbin "graphics/statscreen/vanilla-remix/Tsa_StatscreenPageRight_1.dmp.lz"

.align 2,0
.global Tsa_StatScreenBg1PageNormal
Tsa_StatScreenBg1PageNormal:
	.incbin "graphics/statscreen/vanilla-remix/Tsa_StatscreenPageRight_2.dmp.lz"

.align 2,0
.global Tsa_StatScreenBg1PageShort
Tsa_StatScreenBg1PageShort:
	.incbin "graphics/statscreen/vanilla-remix/Tsa_StatscreenPageRight_3.dmp.lz"
