.section .rodata.reloc_list

.align 2,0

.global pr_PInfoTable
pr_PInfoTable: .word PInfoTable

.global pr_JInfoTable
pr_JInfoTable: .word JInfoTable

.global pr_IInfoTable
pr_IInfoTable: .word IInfoTable

.global gpImg_Icons
gpImg_Icons: .word Img_Icons

.global gpPal_Icons
gpPal_Icons: .word Pal_Icons

.global gpAffinIcons
gpAffinIcons: .word gAffinIcons

.global gpMountIcons
gpMountIcons: .word gMountIcons

.global gpWTypeIcons
gpWTypeIcons: .word gWTypeIcons

.global gpJobGrowthList
gpJobGrowthList: .word gJobGrowthList

.global gpChapterInfoTable
gpChapterInfoTable: .word ChapterInfoTable

.global gpChapterAssets
gpChapterAssets: .word ChapterAssets

.global gpSongTable
gpSongTable: .word gSongTable

.global gpUnitMaxStatusConfigTable
gpUnitMaxStatusConfigTable: .word gUnitMaxStatusConfigTable

.global gpSkillPTable
gpSkillPTable: .word gSkillPTable

.global gpSkillJTable
gpSkillJTable: .word gSkillJTable

.global gpImg_StatScreenSprites
gpImg_StatScreenSprites: .word Img_StatScreenSprites

.global gpPal_StatscreenPageNameFlashing
gpPal_StatscreenPageNameFlashing: .word Pal_StatscreenPageNameFlashing

.global gpSkillExtraInfo
gpSkillExtraInfo: .word gSkillExtraInfo

.global gpSkillInfo
gpSkillInfo: .word gSkillInfo
